ctm-sf-homeloan-app/main/default/objects/Account/fields/CreditScore__c.field-meta.xml
<CustomField>
    <fullName>CreditScore__c</fullName>
    <label>Credit Score</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/Account/fields/CreditScoreID__c.field-meta.xml
<CustomField>
    <fullName>CreditScoreID__c</fullName>
    <label>Credit Score ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/Account/fields/LatestCreditCheckDate__c.field-meta.xml
<CustomField>
    <fullName>LatestCreditCheckDate__c</fullName>
    <label>Latest Credit Check Date</label>
    <type>Date</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/Account/fields/OriginalCreditCheckDate__c.field-meta.xml
<CustomField>
    <fullName>OriginalCreditCheckDate__c</fullName>
    <label>Original Credit Check Date</label>
    <type>Date</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/CreditScore__c.object-meta.xml
<CustomObject>
    <label>Credit Score</label>
    <nameField>
        <label>Credit Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Score</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/fields/CreditScore__c.field-meta.xml
<CustomField>
    <fullName>CreditScore__c</fullName>
    <label>Credit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/fields/CreditScoreId__c.field-meta.xml
<CustomField>
    <fullName>CreditScoreId__c</fullName>
    <label>Credit Score Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/classes/HLA_CreditScoreServiceImp.cls
public with sharing class HLA_CreditScoreServiceImp implements HLA_ICreditScoreService {
  //

  public void requestAccountCreditScoreAssessment(List<Account> accountList) {
    new HLA_CreditScoreAssessmentAsyncProccessor().get(accountList).kickoff();
  }

  public List<Account> selectAccountsDueForCreditAssessment() {
    Date creditCheckDueDate = System.Today().addMonths(-1);
    return Database.query(
      ((AccountsSelector) AccountsSelector.newInstance())
        .newQueryFactory()
        .setCondition(
          'customerId__c != null AND CreditScoreID__c != null AND OriginalCreditCheckDate__c = LAST_N_DAYS:365 AND LatestCreditCheckDate__c <= ' +
          string.valueOf(creditCheckDueDate)
        )
        .toSOQL()
    );
  }

  public void deleteCreditScoresUsingApplicantExternalIds(
    Set<String> applicantExternalIds
  ) {
    ApplicationSObjectUnitOfWork uow = (ApplicationSObjectUnitOfWork) Application.UnitOfWork.newInstance();
    List<CreditScore__c> creditScoresToDelete = HLA_CreditScoreSelector.newInstance()
      .selectCreditScoreUsingApplicantExternalId(applicantExternalIds);
    if (!creditScoresToDelete.isEmpty()) {
      uow.registerDeleted(creditScoresToDelete);
      uow.commitWork();
    }
  }
}