ctm-sf-homeloan-app/main/default/objects/Account/fields/CreditScore__c.field-meta.xml
<CustomField>
    <fullName>CreditScore__c</fullName>
    <label>Credit Score</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/CreditScore__c.object-meta.xml
<CustomObject>
    <label>Credit Score</label>
    <nameField>
        <label>Credit Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Score</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Score</relationshipLabel>
    <relationshipName>Credit_Score</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/fields/CreditScore__c.field-meta.xml
<CustomField>
    <fullName>CreditScore__c</fullName>
    <label>Credit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/fields/LoanApplicant__c.field-meta.xml
<CustomField>
    <fullName>LoanApplicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>LoanApplicant__c</referenceTo>
    <relationshipLabel>Credit Score</relationshipLabel>
    <relationshipName>Credit_Score</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicant__c/LoanApplicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Loan Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicant__c/fields/EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>EmailAddress__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicant__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicant__c/fields/PersonType__c.field-meta.xml
<CustomField>
    <fullName>PersonType__c</fullName>
    <label>Person Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PersonTypes</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicant__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Residential Loan Applications</relationshipLabel>
    <relationshipName>Residential_Loan_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/ApplicationId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationId__c</fullName>
    <externalId>true</externalId>
    <label>Application Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/globalValueSets/PersonTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>831</fullName>
        <label>Borrower</label>
    </customValue>
    <customValue>
        <fullName>832</fullName>
        <label>Guarantor</label>
    </customValue>
    <customValue>
        <fullName>833</fullName>
        <label>Professional Adviser</label>
    </customValue>
    <customValue>
        <fullName>834</fullName>
        <label>Related Party</label>
    </customValue>
    <masterLabel>PersonTypes</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/classes/HLA_CreditScoreSelectorTest.cls
@IsTest
public class HLA_CreditScoreSelectorTest {
  // full name for class was too long

  @IsTest
  public static void should_return_new_instance() {
    // Given
    // When
    HLA_ICreditScoreSelector selector = HLA_CreditScoreSelector.newInstance();
    // Then
    system.assert(selector instanceof HLA_CreditScoreSelector);
  }

  @IsTest
  public static void should_getSObjectFieldList() {
    // Given
    // When
    List<Schema.SObjectField> fields = ((HLA_CreditScoreSelector) HLA_CreditScoreSelector.newInstance())
      .getSObjectFieldList();
    // Then
    system.assert(fields.contains(CreditScore__c.Id));
  }

  @IsTest
  public static void should_getSObjectType() {
    // Given
    // When
    Schema.SObjectType sObjType = ((HLA_CreditScoreSelector) HLA_CreditScoreSelector.newInstance())
      .getSObjectType();
    // Then
    system.assert(sObjType == CreditScore__c.sObjectType);
  }

  @IsTest
  public static void should_getOrderBy() {
    // Given
    // When
    String orderBy = ((HLA_CreditScoreSelector) HLA_CreditScoreSelector.newInstance())
      .getOrderBy();
    // Then
    system.assert(orderBy == 'Name');
  }

  @IsTest
  public static void should_setNewSortOrder() {
    // Given
    // When
    HLA_CreditScoreSelector sel = ((HLA_CreditScoreSelector) HLA_CreditScoreSelector.newInstance())
      .setNewSortOrder('CreatedDate');
    // Then
    system.assert(sel.getOrderBy() == 'CreatedDate');
  }

  @IsTest
  public static void should_select_credit_scores_to_delete() {
    // Given

    IApplicationSObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

    MockHttpResponseGenerator mockHttp = new MockHttpResponseGenerator();
    Test.setMock(HttpCalloutMock.class, mockHttp);

    Account testAcc = new Account(
      firstName = 'Test',
      lastName = 'Account',
      CustomerId__c = '123',
      recordtypeId = HLA_ResidentialLoanApplications.personAccountRTId
    );
    uow.register(testAcc);

    ResidentialLoanApplication__c mockResi = new ResidentialLoanApplication__c(
      Account__c = testAcc.id,
      name = 'test RLA',
      ApplicationId__c = '123'
    );
    uow.register(mockResi, ResidentialLoanApplication__c.Account__c, testAcc);

    LoanApplicant__c testLoanApplicant = new LoanApplicant__c(
      ResidentialLoanApplication__c = mockResi.id,
      EmailAddress__c = 'test@gmail.com',
      PersonType__c = '831',
      ExternalId__c = '1234'
    );
    //uow.register(testLoanApplicant);
    uow.register(
      testLoanApplicant,
      LoanApplicant__c.ResidentialLoanApplication__c,
      mockResi
    );

    CreditScore__c testCreditScore = new CreditScore__c(
      LoanApplicant__c = testLoanApplicant.id,
      name = 'testCred'
    );
    //uow.register(testCreditScore);
    uow.register(
      testCreditScore,
      CreditScore__c.LoanApplicant__c,
      testLoanApplicant
    );
    uow.commitWork();

    // When
    List<CreditScore__c> credList = ((HLA_CreditScoreSelector) HLA_CreditScoreSelector.newInstance())
      .selectCreditScoreUsingApplicantExternalId(new Set<String>{ '1234' });
    // Then
    Assert.isNotNull(credList, 'should have selected credit score');
    Assert.isFalse(credList.isEmpty(), 'should have selected credit score');
  }
}