ctm-sf-homeloan-app/main/default/objects/Account/fields/CreditScoreID__c.field-meta.xml
<CustomField>
    <fullName>CreditScoreID__c</fullName>
    <label>Credit Score ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/Account/fields/LatestCreditCheckDate__c.field-meta.xml
<CustomField>
    <fullName>LatestCreditCheckDate__c</fullName>
    <label>Latest Credit Check Date</label>
    <type>Date</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/Account/fields/OriginalCreditCheckDate__c.field-meta.xml
<CustomField>
    <fullName>OriginalCreditCheckDate__c</fullName>
    <label>Original Credit Check Date</label>
    <type>Date</type>
</CustomField>

ctm-sf-homeloan-app/main/default/classes/HLA_CreditScoreAssessmentSchedule.cls
public class HLA_CreditScoreAssessmentSchedule implements Schedulable {
  //
  public void execute(SchedulableContext sc) {
    // List<Account> accounts = HLA_CreditScoreService.selectAccountsDueForCreditAssessment();
    // HLA_CreditScoreService.requestAccountCreditScoreAssessment(accounts);
    Date creditCheckDueDate = System.Today().addMonths(-1);
    String queryString = 'SELECT CustomerId__c, CreditScoreID__c '+
                                          'FROM Account '+ 
                                          'where customerId__c != null AND CreditScoreID__c != null AND OriginalCreditCheckDate__c = LAST_N_DAYS:365 AND LatestCreditCheckDate__c <= ' +
                                          string.valueOf(creditCheckDueDate);
    new HLA_CreditScoreAssessmentAsyncProccessor().get(queryString).kickoff();
  }
}