ctm-sf-homeloan-app/main/default/objects/Account/fields/CreditScore__c.field-meta.xml
<CustomField>
    <fullName>CreditScore__c</fullName>
    <label>Credit Score</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/Account/fields/CreditScoreID__c.field-meta.xml
<CustomField>
    <fullName>CreditScoreID__c</fullName>
    <label>Credit Score ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/Account/fields/LatestCreditCheckDate__c.field-meta.xml
<CustomField>
    <fullName>LatestCreditCheckDate__c</fullName>
    <label>Latest Credit Check Date</label>
    <type>Date</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/Account/fields/OriginalCreditCheckDate__c.field-meta.xml
<CustomField>
    <fullName>OriginalCreditCheckDate__c</fullName>
    <label>Original Credit Check Date</label>
    <type>Date</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/CreditScore__c.object-meta.xml
<CustomObject>
    <label>Credit Score</label>
    <nameField>
        <label>Credit Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Score</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/fields/CreditScore__c.field-meta.xml
<CustomField>
    <fullName>CreditScore__c</fullName>
    <label>Credit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/fields/CreditScoreId__c.field-meta.xml
<CustomField>
    <fullName>CreditScoreId__c</fullName>
    <label>Credit Score Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/fields/LoanApplicant__c.field-meta.xml
<CustomField>
    <fullName>LoanApplicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>LoanApplicant__c</referenceTo>
    <relationshipLabel>Credit Score</relationshipLabel>
    <relationshipName>Credit_Score</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicant__c/LoanApplicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Loan Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/classes/HLA_CreditScoreServiceTest.cls
@IsTest
public class HLA_CreditScoreServiceTest {
  //

  @TestSetup
  static void setupData() {
    Account testAcct = new Account(
      firstname = 'test',
      lastname = 'acct',
      customerid__c = '123',
      CreditScoreID__c = 'id1',
      OriginalCreditCheckDate__c = System.today().addMonths(-4),
      LatestCreditCheckDate__c = System.today().addMonths(-3)
    );

    insert testAcct;
  }

  @IsTest
  public static void selectAccountsDueForCreditAssessment() {
    List<Account> accounts = HLA_CreditScoreService.selectAccountsDueForCreditAssessment();
    system.debug(accounts);
    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
    Test.StartTest();
    HLA_CreditScoreService.requestAccountCreditScoreAssessment(accounts);
    Test.StopTest();

    Assert.areEqual(
      MockHttpResponseGenerator.calloutCounter,
      2,
      'should have made 2 callouts'
    );
  }

  @IsTest
  public static void should_delete_creditscores_for_applicant_externalids() {
    // Given
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    IApplicationSObjectUnitOfWork mockUoW = (IApplicationSObjectUnitOfWork) mocks.mock(
      ApplicationSObjectUnitOfWork.class
    );
    Application.UnitOfWork.setMock(mockUoW);

    HLA_ICreditScoreSelector mockSelector = (HLA_ICreditScoreSelector) mocks.mock(
      HLA_CreditScoreSelector.class
    );

    CreditScore__c testCreditScore = new CreditScore__c(
      LoanApplicant__c = fflib_IDGenerator.generate(
        LoanApplicant__c.SObjectType
      ),
      name = 'testCred'
    );
    List<CreditScore__c> credList = new List<CreditScore__c>();
    credList.add(testCreditScore);

    Set<String> testStringSet = new Set<String>{ 'test' };

    mocks.startStubbing();
    mocks.when(mockSelector.SObjectType())
      .thenReturn(CreditScore__c.sObjectType);

    mocks.when(
        mockSelector.selectCreditScoreUsingApplicantExternalId(testStringSet)
      )
      .thenReturn(credList);

    mocks.stopStubbing();
    Application.Selector.setMock(mockSelector);

    // When
    Test.StartTest();
    HLA_CreditScoreService.deleteCreditScoresUsingApplicantExternalIds(
      testStringSet
    );
    Test.StopTest();

    // verify
    ((HLA_ICreditScoreSelector) mocks.verify(mockSelector))
      .selectCreditScoreUsingApplicantExternalId(testStringSet);
    ((IApplicationSObjectUnitOfWork) mocks.verify(mockUoW, 1)).commitWork();
  }
}