ctm-sf-homeloan-app/main/default/objects/Account/fields/CreditScore__c.field-meta.xml
<CustomField>
    <fullName>CreditScore__c</fullName>
    <label>Credit Score</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/CreditScore__c.object-meta.xml
<CustomObject>
    <label>Credit Score</label>
    <nameField>
        <label>Credit Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Score</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Score</relationshipLabel>
    <relationshipName>Credit_Score</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/CreditScore__c/fields/CreditScore__c.field-meta.xml
<CustomField>
    <fullName>CreditScore__c</fullName>
    <label>Credit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/OtherAddress__c/OtherAddress__c.object-meta.xml
<CustomObject>
    <label>Other Address</label>
    <nameField>
        <label>Other Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Other Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/OtherAddress__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <type>Address</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/OtherAddress__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Other Addresses</relationshipLabel>
    <relationshipName>Other_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/PropertyReport__c/PropertyReport__c.object-meta.xml
<CustomObject>
    <label>Property Report</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Property Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/PropertyReport__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Property Reports</relationshipLabel>
    <relationshipName>Property_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/PropertyReport__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Residential Loan Applications</relationshipLabel>
    <relationshipName>Residential_Loan_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/ApplicationId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationId__c</fullName>
    <externalId>true</externalId>
    <label>Application Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResponsibleLending__c/ResponsibleLending__c.object-meta.xml
<CustomObject>
    <label>Responsible Lending</label>
    <nameField>
        <label>Responsible Lending Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Responsible Lending</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/ResponsibleLending__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description
  >Residential Loan Application that this Responsible Lending record applies to</description>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Responsible Lending</relationshipLabel>
    <relationshipName>Responsible_Lending</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ThirdParty__c/ThirdParty__c.object-meta.xml
<CustomObject>
    <description
  >Any third party that provides additional information to verify or support an Application</description>
    <label>Third Party</label>
    <nameField>
        <label>Third Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/ThirdParty__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Third Parties</relationshipLabel>
    <relationshipName>Third_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/VOI__c/VOI__c.object-meta.xml
<CustomObject>
    <description>Verification of Identity</description>
    <label>VOI</label>
    <nameField>
        <label>VOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VOI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/VOI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>VOI</relationshipLabel>
    <relationshipName>VOI</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/classes/HLA_TriggerTest.cls
@IsTest
public class HLA_TriggerTest {
  // currently just for trigger coverage

  @TestSetup
  static void makeData() {
    MockHttpResponseGenerator mockHttp = new MockHttpResponseGenerator();
    Test.setMock(HttpCalloutMock.class, mockHttp);

    Account acc = new Account();
    acc.firstname = 'test';
    acc.lastname = 'Account';
    acc.customerId__c = '123';
    insert acc;

    ResidentialLoanApplication__c rla = new ResidentialLoanApplication__c();
    rla.Account__c = acc.id;
    rla.ApplicationId__c = acc.id;
    insert rla;
  }

  private static Account getAccount() {
    return [SELECT id, firstname, lastname, customerId__c FROM Account][0];
  }

  private static ResidentialLoanApplication__c getRLA() {
    return [
      SELECT id, Account__c, ApplicationId__c
      FROM ResidentialLoanApplication__c
    ][0];
  }

  @IsTest
  public static void HLA_voiTriggerTest() {
    // Given
    Account acc = getAccount();

    VOI__c voi = new VOI__c();
    voi.Account__c = acc.id;

    // When
    insert voi;
    // Then
  }

  @IsTest
  public static void HLA_ThirdPartyTriggerTest() {
    // Given

    ThirdParty__c tp = new ThirdParty__c();
    insert tp;

    // When

    // Then
  }

  @IsTest
  public static void HLA_CreditScoreTriggerTest() {
    // Given
    CreditScore__c cs = new CreditScore__c();
    insert cs;
    // When
    // Then
  }

  @IsTest
  public static void HLA_ResponsibleLendingTriggerTest() {
    // Given
    MockHttpResponseGenerator mockHttp = new MockHttpResponseGenerator();
    Test.setMock(HttpCalloutMock.class, mockHttp);

    Account acc = getAccount();

    ResidentialLoanApplication__c rla = getRLA();

    ResponsibleLending__c resp = new ResponsibleLending__c();
    resp.ResidentialLoanApplication__c = rla.id;
    insert resp;

    // When

    // Then
  }

  @IsTest
  public static void HLA_PropertyReportTriggerTest() {
    // Given
    // Id personAccountRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
    //   .get('PersonAccount')
    //   .getRecordTypeId();

    Account acc = getAccount();

    PropertyReport__c pr = new PropertyReport__c();
    pr.Account__c = acc.id;
    pr.Address__c = '80 jephson street';
    insert pr;

    // When

    // Then
  }

  @IsTest
  public static void HLA_OtherAddressTriggerTest() {
    // Given
    MockHttpResponseGenerator mockHttp = new MockHttpResponseGenerator();
    Test.setMock(HttpCalloutMock.class, mockHttp);

    ResidentialLoanApplication__c rla = getRLA();

    OtherAddress__c oa = new OtherAddress__c();
    oa.ResidentialLoanApplication__c = rla.id;
    insert oa;

    // When

    // Then
  }
}