ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Residential Loan Applications</relationshipLabel>
    <relationshipName>Residential_Loan_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/ApplicationId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationId__c</fullName>
    <externalId>true</externalId>
    <label>Application Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/classes/HLA_TaskListEventAsyncProcessorTest.cls
@IsTest
private class HLA_TaskListEventAsyncProcessorTest {
  //

  @IsTest
  static void test_inner_execute_once() {
    MockHttpResponseGenerator mockHttp = new MockHttpResponseGenerator();
    Test.setMock(HttpCalloutMock.class, mockHttp);

    Account mockAcct = new Account(
      Id = fflib_IDgenerator.generate(Account.sObjectType),
      name = 'Test',
      CustomerId__c = '123'
    );
    ResidentialLoanApplication__c mockLoanApp = new ResidentialLoanApplication__c(
      Id = fflib_IDgenerator.generate(
        ResidentialLoanApplication__c.sObjectType
      ),
      Account__c = mockAcct.id,
      ApplicationId__c = 'appid123'
    );
    mockLoanApp = (ResidentialLoanApplication__c) fflib_ApexMocksUtils.setReadOnlyFields(
      mockLoanApp,
      ResidentialLoanApplication__c.class,
      new Map<String, Object>{ 'Account__r' => mockAcct }
    );

    Task mockTask = new Task(
      Id = fflib_IDgenerator.generate(Task.sObjectType),
      whatId = mockLoanApp.id
    );

    List<ResidentialLoanApplication__c> listRLA = new List<ResidentialLoanApplication__c>{
      mockLoanApp
    };

    listRLA = (List<ResidentialLoanApplication__c>) fflib_ApexMocksUtils.makeRelationship(
      'ResidentialLoanApplication__c',
      'Task',
      listRLA,
      'whatId',
      new List<List<Task>>{ new List<Task>{ mockTask } }
    );

    Test.startTest();
    new HLA_TaskListEventAsyncProcessor().get(listRLA).kickoff();
    Test.stopTest();

    assert.areEqual(
      2,
      MockHttpResponseGenerator.calloutCounter,
      'should have made 2 callouts (token fecth + callout)'
    );
  }
}