ctm-sf-homeloan-app/main/default/objects/HLA_TaskListEvent__e/HLA_TaskListEvent__e.object-meta.xml
<CustomObject>
    <description
  >Platform event to represent an Insert or Update to the Residential Home Loan application Task List</description>
    <label>HLA_TaskList Event</label>
    <pluralLabel>HLA_TaskListEvent</pluralLabel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/HLA_TaskListEvent__e/fields/OriginatedInternally__c.field-meta.xml
<CustomField>
    <fullName>OriginatedInternally__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Flag to indicate if this event originated internally</description>
    <label>Originated Internally</label>
    <type>Checkbox</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/HLA_TaskListEvent__e/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <label>Related Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/HLA_TaskListEvent__e/fields/TaskListJSON__c.field-meta.xml
<CustomField>
    <fullName>TaskListJSON__c</fullName>
    <label>Task List JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/classes/HLA_TaskListEventServiceImp.cls
public with sharing class HLA_TaskListEventServiceImp implements HLA_ITaskListEventService {
  private List<HLA_TaskListEvent__e> externalEvents;
  private List<HLA_TaskListEvent__e> internalEvents;
  private List<String> taskListJSON;

  private final IApplicationSObjectUnitOfWork uow;

  public HLA_TaskListEventServiceImp() {
    this.uow = Application.UnitOfWork.newInstance();
  }

  public void processEvents(List<HLA_TaskListEvent__e> taskListEvents) {
    separateExternalFromInternalEvents(taskListEvents);
    updateTasklistFromExternalData();
    exportInternalTaskEventData();
  }

  private void separateExternalFromInternalEvents(
    List<HLA_TaskListEvent__e> taskListEvents
  ) {
    externalEvents = new List<HLA_TaskListEvent__e>();
    internalEvents = new List<HLA_TaskListEvent__e>();

    for (HLA_TaskListEvent__e taskListEvent : taskListEvents) {
      if (taskListEvent.OriginatedInternally__c) {
        internalEvents.add(taskListEvent);
      } else {
        externalEvents.add(taskListEvent);
      }
    }
  }

  private void updateTasklistFromExternalData() {
    if (!externalEvents.isEmpty()) {
      for (HLA_TaskListEvent__e taskListEvent : externalEvents) {
        list<Task> updatedTaskList = (List<Task>) JSON.deserialize(
          taskListEvent.TaskListJSON__c,
          List<Task>.class
        );
        uow.register(updatedTaskList);
      }
      uow.commitwork();
    }
  }

  private void exportInternalTaskEventData() {
    if (!internalEvents.isEmpty()) {
      Nebula.Logger.info('internalEvents', internalEvents);
      Set<id> residentialLoanIds = new Set<id>();
      for (HLA_TaskListEvent__e taskListEvent : internalEvents) {
        residentialLoanIds.add(taskListEvent.RelatedRecordId__c);
      }
      Nebula.Logger.info('residentialLoanIds = ' + residentialLoanIds);

      List<ResidentialLoanApplication__c> rlaList = HLA_ResidentialLoanApplicationsSelector.newInstance()
        .selectByIdWithTaskListWithLoanTracking(residentialLoanIds);
      new HLA_TaskListEventAsyncProcessor().get(rlaList).kickoff();
    }
  }
}