ctm-sf-homeloan-app/main/default/objects/HLA_TaskListEvent__e/HLA_TaskListEvent__e.object-meta.xml
<CustomObject>
    <description
  >Platform event to represent an Insert or Update to the Residential Home Loan application Task List</description>
    <label>HLA_TaskList Event</label>
    <pluralLabel>HLA_TaskListEvent</pluralLabel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/HLA_TaskListEvent__e/fields/OriginatedInternally__c.field-meta.xml
<CustomField>
    <fullName>OriginatedInternally__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Flag to indicate if this event originated internally</description>
    <label>Originated Internally</label>
    <type>Checkbox</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/HLA_TaskListEvent__e/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <label>Related Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Residential Loan Applications</relationshipLabel>
    <relationshipName>Residential_Loan_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/classes/HLA_TaskListEventTriggerTest.cls
@IsTest
public class HLA_TaskListEventTriggerTest {
  //

  @IsTest
  public static void should_handle_trigger_after_insert() {
    // Given
    Account mockAcct = new Account(
      Id = fflib_IDgenerator.generate(Account.sObjectType),
      name = 'Test'
    );
    ResidentialLoanApplication__c mockLoanApp = new ResidentialLoanApplication__c(
      Id = fflib_IDgenerator.generate(
        ResidentialLoanApplication__c.sObjectType
      ),
      Account__c = mockAcct.id
    );

    HLA_TaskListEvent__e mockEventInternal = new HLA_TaskListEvent__e();
    mockEventInternal.OriginatedInternally__c = true;
    mockEventInternal.RelatedRecordId__c = mockLoanApp.id;
    mockEventInternal.OriginatedInternally__c = true;

    List<HLA_TaskListEvent__e> taskListEvents = new List<HLA_TaskListEvent__e>{
      mockEventInternal
    };

    fflib_ApexMocks mocks = new fflib_ApexMocks();
    HLA_ITaskListEventService mockService = (HLA_ITaskListEventService) mocks.mock(
      HLA_ITaskListEventService.class
    );

    Application.Service.setMock(HLA_ITaskListEventService.class, mockService);
    // When

    Test.startTest();
    Database.SaveResult result = EventBus.publish(mockEventInternal);
    Test.stopTest();

    // Then
    //(HLA_ITaskListEventService) mocks.verify(mockService, 1)
    //  .processEvents(taskListEvents);
  }
}