ctm-sf-homeloan-app/main/default/objects/HLA_TaskListEvent__e/HLA_TaskListEvent__e.object-meta.xml
<CustomObject>
    <description
  >Platform event to represent an Insert or Update to the Residential Home Loan application Task List</description>
    <label>HLA_TaskList Event</label>
    <pluralLabel>HLA_TaskListEvent</pluralLabel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/HLA_TaskListEvent__e/fields/OriginatedInternally__c.field-meta.xml
<CustomField>
    <fullName>OriginatedInternally__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Flag to indicate if this event originated internally</description>
    <label>Originated Internally</label>
    <type>Checkbox</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/HLA_TaskListEvent__e/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <label>Related Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/HLA_TaskListEvent__e/fields/TaskListJSON__c.field-meta.xml
<CustomField>
    <fullName>TaskListJSON__c</fullName>
    <label>Task List JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Residential Loan Applications</relationshipLabel>
    <relationshipName>Residential_Loan_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/ApplicationId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationId__c</fullName>
    <externalId>true</externalId>
    <label>Application Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/classes/HLA_TaskListEventServiceTest.cls
@IsTest
public class HLA_TaskListEventServiceTest {
  static String taskListJSON = '[{\"attributes\":{\"type\":\"Task\",\"url\":\"/services/data/v56.0/sobjects/Task/00T8s000001hNaSEAU\"},\"WhatId\":\"a2P8s0000001fVlEAI\",\"Id\":\"00T8s000001hNaSEAU\",\"Status\":\"Completed\",\"Subject\":\"Time to move in. Housewarming party at your place. Whoop Whoop!\",\"ActivityDate\":\"2022-12-12\"}]';

  @IsTest
  public static void should_process_the_events() {
    // Given
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    IApplicationSObjectUnitOfWork mockUoW = (IApplicationSObjectUnitOfWork) mocks.mock(
      ApplicationSObjectUnitOfWork.class
    );
    Application.UnitOfWork.setMock(mockUoW);

    HLA_IResidentialLoanApplicationsSelector mockRLASelector = (HLA_IResidentialLoanApplicationsSelector) mocks.mock(
      HLA_ResidentialLoanApplicationsSelector.class
    );

    Account mockAcct = new Account(
      Id = fflib_IDgenerator.generate(Account.sObjectType),
      name = 'Test',
      CustomerId__c = '123'
    );
    ResidentialLoanApplication__c mockLoanApp = new ResidentialLoanApplication__c(
      Id = fflib_IDgenerator.generate(
        ResidentialLoanApplication__c.sObjectType
      ),
      Account__c = mockAcct.id,
      ApplicationId__c = 'appid123'
    );
    mockLoanApp = (ResidentialLoanApplication__c) fflib_ApexMocksUtils.setReadOnlyFields(
      mockLoanApp,
      ResidentialLoanApplication__c.class,
      new Map<String, Object>{ 'Account__r' => mockAcct }
    );

    Task mockTask = new Task(
      Id = fflib_IDgenerator.generate(Task.sObjectType),
      whatId = mockLoanApp.id
    );

    List<ResidentialLoanApplication__c> listRLA = new List<ResidentialLoanApplication__c>{
      mockLoanApp
    };

    listRLA = (List<ResidentialLoanApplication__c>) fflib_ApexMocksUtils.makeRelationship(
      'ResidentialLoanApplication__c',
      'Task',
      listRLA,
      'whatId',
      new List<List<Task>>{ new List<Task>{ mockTask } }
    );

    HLA_TaskListEvent__e mockEventInternal = new HLA_TaskListEvent__e();
    mockEventInternal.OriginatedInternally__c = true;
    mockEventInternal.RelatedRecordId__c = mockLoanApp.id;
    mockEventInternal.OriginatedInternally__c = true;

    HLA_TaskListEvent__e mockEventExternal = new HLA_TaskListEvent__e();
    mockEventExternal.OriginatedInternally__c = false;
    mockEventExternal.RelatedRecordId__c = mockLoanApp.id;
    mockEventExternal.TaskListJSON__c = taskListJSON;

    List<HLA_TaskListEvent__e> taskListEvents = new List<HLA_TaskListEvent__e>{
      mockEventInternal,
      mockEventExternal
    };

    mocks.startStubbing();
    mocks.when(mockRLASelector.sObjectType())
      .thenReturn(ResidentialLoanApplication__c.SObjectType);
    mocks.when(
        mockRLASelector
          .selectByIdWithTaskListWithLoanTracking(new Set<id>{ mockLoanApp.id })
      )
      .thenReturn(listRLA);

    mocks.stopStubbing();

    Application.Selector.setMock(mockRLASelector);
    test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

    // When
    test.startTest();
    HLA_TaskListEventService.processEvents(taskListEvents);
    test.stopTest();

    // Then
    ((IApplicationSObjectUnitOfWork) mocks.verify(mockUoW, 1)).commitwork();
  }
}