ctm-sf-homeloan-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/Loan__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanCost__c/LoanCost__c.object-meta.xml
<CustomObject>
    <label>Loan Cost</label>
    <nameField>
        <label>Loan Cost Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanCost__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanCost__c/fields/isDirty__c.field-meta.xml
<CustomField>
    <fullName>isDirty__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate when this records data is not in sync with the Web Application</description>
    <inlineHelpText>Flag to indicate when this records data is not in sync with the Web Application</inlineHelpText>
    <label>isDirty</label>
    <type>Checkbox</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanCost__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loan Costs</relationshipLabel>
    <relationshipName>Loan_Costs</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanCost__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Costs</relationshipLabel>
    <relationshipName>Loan_Costs</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanCost__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CostTypes</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/classes/HLA_LoanCostsSelector.cls
public inherited sharing class HLA_LoanCostsSelector extends ApplicationSObjectSelector implements HLA_ILoanCostsSelector {
  private String newOrderByField;
  private static String DEFAULT_ORDERBY_FIELD = 'Name';

  public static HLA_ILoanCostsSelector newInstance() {
    return (HLA_ILoanCostsSelector) Application.Selector.newInstance(
      LoanCost__c.SObjectType
    );
  }

  // the list of fields to be included in query
  public override List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      LoanCost__c.Id,
      LoanCost__c.Name,
      LoanCost__c.ExternalId__c,
      LoanCost__c.isDirty__c,
      LoanCost__c.Amount__c,
      LoanCost__c.Loan__c,
      LoanCost__c.ResidentialLoanApplication__c,
      LoanCost__c.Type__c
    };
  }

  // SObject type
  public Schema.SObjectType getSObjectType() {
    return LoanCost__c.sObjectType;
  }

  private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
    return new List<Schema.SObjectField>{};
  }

  public override String getOrderBy() {
    if (newOrderByField != null) {
      DEFAULT_ORDERBY_FIELD = newOrderByField;
    }
    return DEFAULT_ORDERBY_FIELD;
  }

  public HLA_LoanCostsSelector setNewSortOrder(String fieldToOrderBy) {
    this.newOrderByField = fieldToOrderBy;
    return this;
  }

  /**
   * We will return List<Sobjects> and leave it to the caller to instatiate a Map if they need easy access to Id's
   */
}