ctm-sf-homeloan-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanEquityRelease__c/LoanEquityRelease__c.object-meta.xml
<CustomObject>
    <label>Loan Equity Release</label>
    <nameField>
        <label>Loan Equity Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Equity Release</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanEquityRelease__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanEquityRelease__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanEquityRelease__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loan Equity Release</relationshipLabel>
    <relationshipName>Loan_Equity_Release</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanEquityRelease__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquityReleaseTypes</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/globalValueSets/EquityReleaseTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>607</fullName>
        <label>Minor property renovations</label>
    </customValue>
    <customValue>
        <fullName>608</fullName>
        <label>Cash out for personal use</label>
    </customValue>
    <customValue>
        <fullName>610</fullName>
        <label>Cash out for business or other investment purposes</label>
    </customValue>
    <customValue>
        <fullName>611</fullName>
        <label>Cash out for property investment purposes</label>
    </customValue>
    <masterLabel>EquityReleaseTypes</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/classes/HLA_LoanEquityReleasesSelector.cls
public inherited sharing class HLA_LoanEquityReleasesSelector extends ApplicationSObjectSelector implements HLA_ILoanEquityReleasesSelector {
  private String newOrderByField;
  private static String DEFAULT_ORDERBY_FIELD = 'Name';

  public static HLA_ILoanEquityReleasesSelector newInstance() {
    return (HLA_ILoanEquityReleasesSelector) Application.Selector.newInstance(
      LoanEquityRelease__c.SObjectType
    );
  }

  // the list of fields to be included in query
  public override List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      LoanEquityRelease__c.Id,
      LoanEquityRelease__c.Name,
      LoanEquityRelease__c.ExternalId__c,
      LoanEquityRelease__c.isDirty__c,
      LoanEquityRelease__c.Amount__c,
      LoanEquityRelease__c.Loan__c,
      LoanEquityRelease__c.Type__c
    };
  }

  // SObject type
  public Schema.SObjectType getSObjectType() {
    return LoanEquityRelease__c.sObjectType;
  }

  private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
    return new List<Schema.SObjectField>{};
  }

  public override String getOrderBy() {
    if (newOrderByField != null) {
      DEFAULT_ORDERBY_FIELD = newOrderByField;
    }
    return DEFAULT_ORDERBY_FIELD;
  }

  public HLA_LoanEquityReleasesSelector setNewSortOrder(String fieldToOrderBy) {
    this.newOrderByField = fieldToOrderBy;
    return this;
  }

  /**
   * We will return List<Sobjects> and leave it to the caller to instatiate a Map if they need easy access to Id's
   */
}