ctm-sf-homeloan-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/Loan__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/LoanApplicationLiability__c.object-meta.xml
<CustomObject>
    <label>Loan Application Liability</label>
    <nameField>
        <label>Loan Application Liability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/isDirty__c.field-meta.xml
<CustomField>
    <fullName>isDirty__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Flag to indicate when this records data is not in sync with the Web Application</description>
    <inlineHelpText
  >Flag to indicate when this records data is not in sync with the Web Application</inlineHelpText>
    <label>isDirty</label>
    <type>Checkbox</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Application Liabilities</relationshipLabel>
    <relationshipName>Loan_Application_Liabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanSplit__c/LoanSplit__c.object-meta.xml
<CustomObject>
    <label>Loan Split</label>
    <nameField>
        <label>Loan Split Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Splits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanSplit__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanSplit__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loan Splits</relationshipLabel>
    <relationshipName>Loan_Splits</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanSplit__c/fields/LoanApplicationLiability__c.field-meta.xml
<CustomField>
    <fullName>LoanApplicationLiability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application Liability</label>
    <referenceTo>LoanApplicationLiability__c</referenceTo>
    <relationshipLabel>Loan Splits</relationshipLabel>
    <relationshipName>Loan_Splits</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanSplit__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Splits</relationshipLabel>
    <relationshipName>Loan_Splits</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/classes/HLA_LoanSplitsSelector.cls
public inherited sharing class HLA_LoanSplitsSelector extends ApplicationSObjectSelector implements HLA_ILoanSplitsSelector {
  private String newOrderByField;
  private static String DEFAULT_ORDERBY_FIELD = 'Name';

  public static HLA_ILoanSplitsSelector newInstance() {
    return (HLA_ILoanSplitsSelector) Application.Selector.newInstance(
      LoanSplit__c.SObjectType
    );
  }

  // the list of fields to be included in query
  public override List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      LoanSplit__c.Id,
      LoanSplit__c.Name,
      LoanSplit__c.ExternalId__c,
      LoanSplit__c.isDirty__c,
      LoanSplit__c.Loan__c,
      LoanSplit__c.LoanApplicationLiability__c,
      LoanSplit__c.ResidentialLoanApplication__c
    };
  }

  // SObject type
  public Schema.SObjectType getSObjectType() {
    return LoanSplit__c.sObjectType;
  }

  private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
    return new List<Schema.SObjectField>{};
  }

  public override String getOrderBy() {
    if (newOrderByField != null) {
      DEFAULT_ORDERBY_FIELD = newOrderByField;
    }
    return DEFAULT_ORDERBY_FIELD;
  }

  public HLA_LoanSplitsSelector setNewSortOrder(String fieldToOrderBy) {
    this.newOrderByField = fieldToOrderBy;
    return this;
  }

  /**
   * We will return List<Sobjects> and leave it to the caller to instatiate a Map if they need easy access to Id's
   */
}