ctm-sf-homeloan-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/Loan__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanContribution__c/LoanContribution__c.object-meta.xml
<CustomObject>
    <label>Loan Contribution</label>
    <nameField>
        <label>Loan Contribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Contributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanContribution__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanContribution__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loan Contributions</relationshipLabel>
    <relationshipName>Loan_Contributions</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanContribution__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Contributions</relationshipLabel>
    <relationshipName>Loan_Contributions</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanContribution__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ContributionType</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/globalValueSets/ContributionType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>64</fullName>
        <label>Deposit</label>
    </customValue>
    <customValue>
        <fullName>65</fullName>
        <label>Cash At Bank</label>
    </customValue>
    <customValue>
        <fullName>66</fullName>
        <label>Sales Proceeds</label>
    </customValue>
    <customValue>
        <fullName>67</fullName>
        <label>First Home Buyers Grant</label>
    </customValue>
    <customValue>
        <fullName>68</fullName>
        <label>Other Grants</label>
    </customValue>
    <customValue>
        <fullName>69</fullName>
        <label>Other contribution type</label>
    </customValue>
    <customValue>
        <fullName>70</fullName>
        <label>Equity in existing property</label>
    </customValue>
    <masterLabel>ContributionType</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/classes/HLA_LoanContributionsSelector.cls
public inherited sharing class HLA_LoanContributionsSelector extends ApplicationSObjectSelector implements HLA_ILoanContributionsSelector {
  private String newOrderByField;
  private static String DEFAULT_ORDERBY_FIELD = 'Name';

  public static HLA_ILoanContributionsSelector newInstance() {
    return (HLA_ILoanContributionsSelector) Application.Selector.newInstance(
      LoanContribution__c.SObjectType
    );
  }

  // the list of fields to be included in query
  public override List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      LoanContribution__c.Id,
      LoanContribution__c.Name,
      LoanContribution__c.ExternalId__c,
      LoanContribution__c.isDirty__c,
      LoanContribution__c.amount__c,
      LoanContribution__c.Loan__c,
      LoanContribution__c.Type__c,
      LoanContribution__c.ResidentialLoanApplication__c
    };
  }

  // SObject type
  public Schema.SObjectType getSObjectType() {
    return LoanContribution__c.sObjectType;
  }

  private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
    return new List<Schema.SObjectField>{};
  }

  public override String getOrderBy() {
    if (newOrderByField != null) {
      DEFAULT_ORDERBY_FIELD = newOrderByField;
    }
    return DEFAULT_ORDERBY_FIELD;
  }

  public HLA_LoanContributionsSelector setNewSortOrder(String fieldToOrderBy) {
    this.newOrderByField = fieldToOrderBy;
    return this;
  }

  /**
   * We will return List<Sobjects> and leave it to the caller to instatiate a Map if they need easy access to Id's
   */
}