ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/LoanApplicationLiability__c.object-meta.xml
<CustomObject>
    <label>Loan Application Liability</label>
    <nameField>
        <label>Loan Application Liability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Application Liabilities</relationshipLabel>
    <relationshipName>Loan_Application_Liabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/classes/HLA_AddFinancialstoRLAServiceTest.cls
@isTest
public class HLA_AddFinancialstoRLAServiceTest {
  @isTest
  public static void createsPayloadandDoesHttpCallout() {
    TestDataFactory.makeData('LoanApplicationLiability');
    LoanApplicationLiability__c lasset = [
      SELECT id, name, ReferenceId__c, ResidentialLoanApplication__c
      FROM LoanApplicationLiability__c
      WHERE ReferenceId__c != ''
      LIMIT 1
    ];

    MockHttpResponseGenerator mockHttp = new MockHttpResponseGenerator();
    MockHttpResponseGenerator.statusCodetoReturn = 301;

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, mockHttp);
    HLA_AddFinancialstoRLAService.createPayloadFlowCreatedFinancialRecords(
      lasset.ReferenceId__c,
      lasset.ResidentialLoanApplication__c
    );

    Test.stopTest();
    system.assert(
      MockHttpResponseGenerator.calloutCounter == 6,
      'should have generated 6 mock callouts'
    );
  }
}