ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/LoanApplicationLiability__c.object-meta.xml
<CustomObject>
    <label>Loan Application Liability</label>
    <nameField>
        <label>Loan Application Liability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/InitialLoanAmount__c.field-meta.xml
<CustomField>
    <fullName>InitialLoanAmount__c</fullName>
    <label>Initial Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/Institution__c.field-meta.xml
<CustomField>
    <fullName>Institution__c</fullName>
    <label>Institution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CreditInstitutions</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/InterestCapitalised__c.field-meta.xml
<CustomField>
    <fullName>InterestCapitalised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Interest Capitalised</label>
    <type>Checkbox</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/InterestRate__c.field-meta.xml
<CustomField>
    <fullName>InterestRate__c</fullName>
    <description
  >The interest rate for the liability (where applicable).</description>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/isDirty__c.field-meta.xml
<CustomField>
    <fullName>isDirty__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Flag to indicate when this records data is not in sync with the Web Application</description>
    <inlineHelpText
  >Flag to indicate when this records data is not in sync with the Web Application</inlineHelpText>
    <label>isDirty</label>
    <type>Checkbox</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/LoanLimit__c.field-meta.xml
<CustomField>
    <fullName>LoanLimit__c</fullName>
    <label>Loan Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/OutstandingBalance__c.field-meta.xml
<CustomField>
    <fullName>OutstandingBalance__c</fullName>
    <label>Outstanding Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/RepaymentAmount__c.field-meta.xml
<CustomField>
    <fullName>RepaymentAmount__c</fullName>
    <label>Repayment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Application Liabilities</relationshipLabel>
    <relationshipName>Loan_Application_Liabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LiabilityTypes</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/InterestRate__c.field-meta.xml
<CustomField>
    <fullName>InterestRate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

ctm-sf-homeloan-app/main/default/globalValueSets/LiabilityTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>774</fullName>
        <label>Credit or Store Cards</label>
    </customValue>
    <customValue>
        <fullName>775</fullName>
        <label>Vehicle lease</label>
    </customValue>
    <customValue>
        <fullName>776</fullName>
        <label>Personal loan</label>
    </customValue>
    <customValue>
        <fullName>777</fullName>
        <label>Personal Overdraft</label>
    </customValue>
    <customValue>
        <fullName>778</fullName>
        <label>HECS / HELP debt</label>
    </customValue>
    <customValue>
        <fullName>779</fullName>
        <label>ATO or Centerlink debt</label>
    </customValue>
    <customValue>
        <fullName>780</fullName>
        <label>Other liability</label>
    </customValue>
    <customValue>
        <fullName>781</fullName>
        <label>Residential owner occupied mortgage</label>
    </customValue>
    <customValue>
        <fullName>782</fullName>
        <label>Residential investment mortgage</label>
    </customValue>
    <customValue>
        <fullName>783</fullName>
        <label>Commercial owner occupied mortgage</label>
    </customValue>
    <customValue>
        <fullName>784</fullName>
        <label>Commercial investment mortgage</label>
    </customValue>
    <customValue>
        <fullName>785</fullName>
        <label>Margin loan</label>
    </customValue>
    <masterLabel>LiabilityTypes</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/classes/HLA_LoanApplicationLiabilitiesSelector.cls
public inherited sharing class HLA_LoanApplicationLiabilitiesSelector extends ApplicationSObjectSelector implements HLA_ILoanApplicationLiabilitiesSelector {
  private String newOrderByField;
  private static String DEFAULT_ORDERBY_FIELD = 'Name';

  public static HLA_ILoanApplicationLiabilitiesSelector newInstance() {
    return (HLA_ILoanApplicationLiabilitiesSelector) Application.Selector.newInstance(
      LoanApplicationLiability__c.SObjectType
    );
  }

  // the list of fields to be included in query
  public override List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      LoanApplicationLiability__c.ResidentialLoanApplication__c,
      LoanApplicationLiability__c.Id,
      LoanApplicationLiability__c.Name,
      LoanApplicationLiability__c.ExternalId__c,
      LoanApplicationLiability__c.ReferenceId__c,
      LoanApplicationLiability__c.Description__c,
      LoanApplicationLiability__c.InitialLoanAmount__c,
      LoanApplicationLiability__c.Institution__c,
      LoanApplicationLiability__c.InterestCapitalised__c,
      LoanApplicationLiability__c.InterestRate__c,
      LoanApplicationLiability__c.LoanLimit__c,
      LoanApplicationLiability__c.OutstandingBalance__c,
      LoanApplicationLiability__c.RepaymentAmount__c,
      LoanApplicationLiability__c.Type__c,
      LoanApplicationLiability__c.isDirty__c
    };
  }

  // SObject type
  public Schema.SObjectType getSObjectType() {
    return LoanApplicationLiability__c.sObjectType;
  }

  @TestVisible
  private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
    return new List<Schema.SObjectField>{};
  }

  public override String getOrderBy() {
    if (newOrderByField != null) {
      DEFAULT_ORDERBY_FIELD = newOrderByField;
    }
    return DEFAULT_ORDERBY_FIELD;
  }

  public HLA_LoanApplicationLiabilitiesSelector setNewSortOrder(
    String fieldToOrderBy
  ) {
    this.newOrderByField = fieldToOrderBy;
    return this;
  }

  /**
   * We will return List<Sobjects> and leave it to the caller to instatiate a Map if they need easy access to Id's
   */
  public List<LoanApplicationLiability__c> selectLoanApplicationLiabilitiesByReferenceId(
    String referenceId,
    String applId
  ) {
    return (List<LoanApplicationLiability__c>) Database.query(
      newQueryFactory()
        .selectfield('Name')
        .setCondition(
          'ReferenceId__c = :referenceId AND ResidentialLoanApplication__c = :applId'
        )
        .toSOQL()
    );
  }
}