ctm-sf-homeloan-app/main/default/objects/LoanApplicantExpense__c/LoanApplicantExpense__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant Expense</label>
    <nameField>
        <label>Loan Applicant Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicant Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantExpense__c/fields/AId__c.field-meta.xml
<CustomField>
    <fullName>AId__c</fullName>
    <formula>LoanApplicant__r.ExternalId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AId</label>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantExpense__c/fields/BId__c.field-meta.xml
<CustomField>
    <fullName>BId__c</fullName>
    <formula>LoanApplicationExpense__r.ExternalId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BId</label>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantExpense__c/fields/ExpenseSubType__c.field-meta.xml
<CustomField>
    <fullName>ExpenseSubType__c</fullName>
    <label>Expense SubType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ExpenseSubTypes</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantExpense__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantExpense__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description
  >The frequency of the expense payments. Expenses of type ‘Credit Card Limit’ must
        have a frequency of annually.</description>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periods</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantExpense__c/fields/OutstandingAmt__c.field-meta.xml
<CustomField>
    <fullName>OutstandingAmt__c</fullName>
    <description
  >The amount left to pay for the expense. Required for refinanced expenses and expenses with type ‘Mortgage Loan’</description>
    <label>Outstanding Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantExpense__c/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <description>Lookup to Loan Application Expense Reference Field</description>
    <formula>LoanApplicationExpense__r.ReferenceId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ReferenceId</label>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantExpense__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Applicant Expenses</relationshipLabel>
    <relationshipName>Loan_Applicant_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/globalValueSets/ExpenseSubTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>619</fullName>
        <label>Owner Occupied Property - Residential Mortgage Loan Payments</label>
    </customValue>
    <customValue>
        <fullName>620</fullName>
        <label>Investment Property - Residential Mortgage Loan Payments</label>
    </customValue>
    <customValue>
        <fullName>621</fullName>
        <label>Investment Property - Commercial Mortgage Loan Payments</label>
    </customValue>
    <customValue>
        <fullName>622</fullName>
        <label>Card Payments</label>
    </customValue>
    <customValue>
        <fullName>623</fullName>
        <label>Vehicle Payments</label>
    </customValue>
    <customValue>
        <fullName>624</fullName>
        <label>Personal Loan Payments</label>
    </customValue>
    <customValue>
        <fullName>625</fullName>
        <label>Overdraft Payments</label>
    </customValue>
    <customValue>
        <fullName>626</fullName>
        <label>Margin Loan Payments</label>
    </customValue>
    <customValue>
        <fullName>627</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>628</fullName>
        <label>ATO tax debt or Centrelink debt Repayments</label>
    </customValue>
    <customValue>
        <fullName>1639</fullName>
        <label>HECS HELP</label>
    </customValue>
    <customValue>
        <fullName>676</fullName>
        <label>Child Support and Spousal Maintenance</label>
    </customValue>
    <customValue>
        <fullName>677</fullName>
        <label>Clothing &amp; Personal Care</label>
    </customValue>
    <customValue>
        <fullName>678</fullName>
        <label>Education &amp; Childcare</label>
    </customValue>
    <customValue>
        <fullName>679</fullName>
        <label>Food &amp; Groceries</label>
    </customValue>
    <customValue>
        <fullName>680</fullName>
        <label>Insurance</label>
    </customValue>
    <customValue>
        <fullName>681</fullName>
        <label>Investment Property Expenses</label>
    </customValue>
    <customValue>
        <fullName>682</fullName>
        <label>Medical &amp; Health</label>
    </customValue>
    <customValue>
        <fullName>683</fullName>
        <label>Phone, Internet &amp; Media</label>
    </customValue>
    <customValue>
        <fullName>684</fullName>
        <label>Recreation &amp; Entertainment</label>
    </customValue>
    <customValue>
        <fullName>685</fullName>
        <label>Rent and Board</label>
    </customValue>
    <customValue>
        <fullName>686</fullName>
        <label>Transport</label>
    </customValue>
    <customValue>
        <fullName>687</fullName>
        <label>Primary Residence Utilities and Running Costs</label>
    </customValue>
    <customValue>
        <fullName>688</fullName>
        <label>Other Regular Expenses</label>
    </customValue>
    <masterLabel>ExpenseSubTypes</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/globalValueSets/Periods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>824</fullName>
        <label>Weekly</label>
    </customValue>
    <customValue>
        <fullName>825</fullName>
        <label>Fortnightly</label>
    </customValue>
    <customValue>
        <fullName>826</fullName>
        <label>Monthly</label>
    </customValue>
    <customValue>
        <fullName>827</fullName>
        <label>Quarterly</label>
    </customValue>
    <customValue>
        <fullName>828</fullName>
        <label>Half Yearly</label>
    </customValue>
    <customValue>
        <fullName>829</fullName>
        <label>Annually</label>
    </customValue>
    <masterLabel>Periods</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/classes/HLA_LoanApplicantExpensesSelector.cls
public inherited sharing class HLA_LoanApplicantExpensesSelector extends ApplicationSObjectSelector implements HLA_ILoanApplicantExpensesSelector {
  private String newOrderByField;
  private static String DEFAULT_ORDERBY_FIELD = 'Name';

  public static HLA_ILoanApplicantExpensesSelector newInstance() {
    return (HLA_ILoanApplicantExpensesSelector) Application.Selector.newInstance(
      LoanApplicantExpense__c.SObjectType
    );
  }

  // the list of fields to be included in query
  public override List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      LoanApplicantExpense__c.ResidentialLoanApplication__c,
      LoanApplicantExpense__c.Id,
      LoanApplicantExpense__c.Name,
      LoanApplicantExpense__c.ReferenceId__c,
      LoanApplicantExpense__c.ExternalId__c,
      LoanApplicantExpense__c.AId__c,
      LoanApplicantExpense__c.BId__c,
      LoanApplicantExpense__c.Percentage__c,
      LoanApplicantExpense__c.ExpenseType__c,
      LoanApplicantExpense__c.ExpenseSubType__c,
      LoanApplicantExpense__c.Frequency__c,
      LoanApplicantExpense__c.OutstandingAmt__c,
      LoanApplicantExpense__c.Amount__c,
      LoanApplicantExpense__c.isDirty__c
    };
  }

  // SObject type
  public Schema.SObjectType getSObjectType() {
    return LoanApplicantExpense__c.sObjectType;
  }

  @TestVisible
  private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
    return new List<Schema.SObjectField>{};
  }

  public override String getOrderBy() {
    if (newOrderByField != null) {
      DEFAULT_ORDERBY_FIELD = newOrderByField;
    }
    return DEFAULT_ORDERBY_FIELD;
  }

  public HLA_LoanApplicantExpensesSelector setNewSortOrder(
    String fieldToOrderBy
  ) {
    this.newOrderByField = fieldToOrderBy;
    return this;
  }

  /**
   * We will return List<Sobjects> and leave it to the caller to instatiate a Map if they need easy access to Id's
   */

  public List<LoanApplicantExpense__c> selectLoanApplicantExpensesByReferenceId(
    String referenceId,
    String applId
  ) {
    return (List<LoanApplicantExpense__c>) Database.query(
      newQueryFactory()
        .selectfield('Name')
        .setCondition(
          'ReferenceId__c = :referenceId AND ResidentialLoanApplication__c = :applId'
        )
        .toSOQL()
    );
  }
}