ctm-sf-homeloan-app/main/default/objects/RelatedParty__c/RelatedParty__c.object-meta.xml
<CustomObject>
    <label>Related Party</label>
    <nameField>
        <label>Related Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/RelatedParty__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Parties</relationshipLabel>
    <relationshipName>Related_Parties</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/RelatedParty__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

ctm-sf-homeloan-app/main/default/classes/HLA_RelatedPartyServiceTest.cls
@IsTest
public class HLA_RelatedPartyServiceTest {
  @IsTest
  public static void should_parse_and_create_related_party() {
    // Given
    Account Acct = new Account(lastname = 'test', firstname = 'fred');
    insert Acct;
    String relatedPartyJSON = '{"name":"test", "Email__c":"test@test.com","account__c":"' + Acct.id + '"}';

    // When

    RelatedParty__c relParty = HLA_RelatedPartyService.parseAndCreateNewRelatedParty(
      relatedPartyJSON
    );
    // Then
    relParty = [SELECT name FROM RelatedParty__c WHERE Id = :relParty.id];
    system.assertEquals(
      'test',
      relParty.name,
      'should have parsed and inserted loan scenarion'
    );
  }
}