ctm-sf-homeloan-app/main/default/objects/LoanApplicationExpense__c/LoanApplicationExpense__c.object-meta.xml
<CustomObject>
    <label>Loan Application Expense</label>
    <nameField>
        <label>Loan Application Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Expense</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationExpense__c/fields/ExpenseDebtType__c.field-meta.xml
<CustomField>
    <fullName>ExpenseDebtType__c</fullName>
    <label>Expense Debt Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ExpenseDebtTypes</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationExpense__c/fields/ExpenseType__c.field-meta.xml
<CustomField>
    <fullName>ExpenseType__c</fullName>
    <label>Expense Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ExpenseTypes</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationExpense__c/fields/OutstandingAmount__c.field-meta.xml
<CustomField>
    <fullName>OutstandingAmount__c</fullName>
    <label>Outstanding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationExpense__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Application Expense</relationshipLabel>
    <relationshipName>Loan_Application_Expense</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/globalValueSets/ExpenseDebtTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>619</fullName>
        <label>Owner Occupied Property - Residential Mortgage Loan Payments</label>
    </customValue>
    <customValue>
        <fullName>620</fullName>
        <label>Investment Property - Residential Mortgage Loan Payments</label>
    </customValue>
    <customValue>
        <fullName>621</fullName>
        <label>Investment Property - Commercial Mortgage Loan Payments</label>
    </customValue>
    <customValue>
        <fullName>622</fullName>
        <label>Card Payments</label>
    </customValue>
    <customValue>
        <fullName>623</fullName>
        <label>Vehicle Payments</label>
    </customValue>
    <customValue>
        <fullName>624</fullName>
        <label>Personal Loan Payments</label>
    </customValue>
    <customValue>
        <fullName>625</fullName>
        <label>Overdraft Payments</label>
    </customValue>
    <customValue>
        <fullName>626</fullName>
        <label>Margin Loan Payments</label>
    </customValue>
    <customValue>
        <fullName>627</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>628</fullName>
        <label>ATO tax debt or Centrelink debt Repayments</label>
    </customValue>
    <customValue>
        <fullName>1639</fullName>
        <label>HECS HELP</label>
    </customValue>
    <masterLabel>ExpenseDebtTypes</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/globalValueSets/ExpenseTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>689</fullName>
        <label>Debt Expense</label>
    </customValue>
    <customValue>
        <fullName>690</fullName>
        <label>Living Expense</label>
    </customValue>
    <masterLabel>ExpenseTypes</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/classes/HLA_LoanApplicationExpensesSelector.cls
public inherited sharing class HLA_LoanApplicationExpensesSelector extends ApplicationSObjectSelector implements HLA_ILoanApplicationExpensesSelector {
  private String newOrderByField;
  private static String DEFAULT_ORDERBY_FIELD = 'Name';

  public static HLA_ILoanApplicationExpensesSelector newInstance() {
    return (HLA_ILoanApplicationExpensesSelector) Application.Selector.newInstance(
      LoanApplicationExpense__c.SObjectType
    );
  }

  // the list of fields to be included in query
  public override List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      LoanApplicationExpense__c.ResidentialLoanApplication__c,
      LoanApplicationExpense__c.Id,
      LoanApplicationExpense__c.Name,
      LoanApplicationExpense__c.ExternalId__c,
      LoanApplicationExpense__c.ReferenceId__c,
      LoanApplicationExpense__c.Amount__c,
      LoanApplicationExpense__c.OutstandingAmount__c,
      LoanApplicationExpense__c.Frequency__c,
      LoanApplicationExpense__c.ExpenseDebtType__c,
      LoanApplicationExpense__c.ExpenseType__c,
      LoanApplicationExpense__c.isDirty__c
    };
  }

  // SObject type
  public Schema.SObjectType getSObjectType() {
    return LoanApplicationExpense__c.sObjectType;
  }

  @TestVisible private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
    return new List<Schema.SObjectField>{};
  }

  public override String getOrderBy() {
    if (newOrderByField != null) {
      DEFAULT_ORDERBY_FIELD = newOrderByField;
    }
    return DEFAULT_ORDERBY_FIELD;
  }

  public HLA_LoanApplicationExpensesSelector setNewSortOrder(
    String fieldToOrderBy
  ) {
    this.newOrderByField = fieldToOrderBy;
    return this;
  }

  /**
   * We will return List<Sobjects> and leave it to the caller to instatiate a Map if they need easy access to Id's
   */
  public List<LoanApplicationExpense__c> selectLoanApplicationExpensesByReferenceId(
    String referenceId,
    String applId
  ) {
    return (List<LoanApplicationExpense__c>) Database.query(
      newQueryFactory()
        .selectfield('Name')
        .setCondition(
          'ReferenceId__c = :referenceId AND ResidentialLoanApplication__c = :applId'
        )
        .toSOQL()
    );
  }
}