ctm-sf-homeloan-app/main/default/objects/LoanApplicationAsset__c/LoanApplicationAsset__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Loan_Application_Asset_Compact_Layout</compactLayoutAssignment>
    <label>Loan Application Asset</label>
    <nameField>
        <label>Loan Application Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationAsset__c/fields/AssetSavingsAndDepositsType__c.field-meta.xml
<CustomField>
    <fullName>AssetSavingsAndDepositsType__c</fullName>
    <label>Asset Savings And Deposits Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AssetSavingsAndDepositsType</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationAsset__c/fields/AssetSuperannuationType__c.field-meta.xml
<CustomField>
    <fullName>AssetSuperannuationType__c</fullName>
    <label>Asset Superannuation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AssetSuperannuationType</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationAsset__c/fields/AssetType__c.field-meta.xml
<CustomField>
    <fullName>AssetType__c</fullName>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AssetTypes</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationAsset__c/fields/AssetVehicleType__c.field-meta.xml
<CustomField>
    <fullName>AssetVehicleType__c</fullName>
    <label>Asset Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AssetVehicleType</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationAsset__c/fields/CommercialPropertyType__c.field-meta.xml
<CustomField>
    <fullName>CommercialPropertyType__c</fullName>
    <label>Commercial Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PropertyCommercialTypes</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationAsset__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationAsset__c/fields/EstimatedValue__c.field-meta.xml
<CustomField>
    <fullName>EstimatedValue__c</fullName>
    <label>Estimated Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationAsset__c/fields/isSecurityForLoanFinancingIt__c.field-meta.xml
<CustomField>
    <fullName>isSecurityForLoanFinancingIt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Security For Loan Financing It</label>
    <type>Checkbox</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationAsset__c/fields/Motorcycles__c.field-meta.xml
<CustomField>
    <fullName>Motorcycles__c</fullName>
    <label>Motorcycles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Motorcycles</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationAsset__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Application Assets</relationshipLabel>
    <relationshipName>Loan_Application_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationAsset__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicles</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/globalValueSets/AssetSavingsAndDepositsType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>17</fullName>
        <label>Cash management trust</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>Cheque account</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>Savings account</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Term deposit</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Other account</label>
    </customValue>
    <customValue>
        <fullName>1658</fullName>
        <label>Deposit already paid</label>
    </customValue>
    <masterLabel>AssetSavingsAndDepositsType</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/globalValueSets/AssetSuperannuationType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>22</fullName>
        <label>Approved Deposit Fund</label>
    </customValue>
    <customValue>
        <fullName>23</fullName>
        <label>Corporate Fund</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>Eligible Rollover Fund</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>Industry Fund</label>
    </customValue>
    <customValue>
        <fullName>26</fullName>
        <label>Public Sector Fund</label>
    </customValue>
    <customValue>
        <fullName>27</fullName>
        <label>Retail Fund</label>
    </customValue>
    <customValue>
        <fullName>28</fullName>
        <label>Retirement Savings Account</label>
    </customValue>
    <customValue>
        <fullName>29</fullName>
        <label>Self Managed Superannuation Fund</label>
    </customValue>
    <masterLabel>AssetSuperannuationType</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/globalValueSets/AssetTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>30</fullName>
        <label>Vehicle</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>Savings and Deposits</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>Investments</label>
    </customValue>
    <customValue>
        <fullName>33</fullName>
        <label>Superannuation</label>
    </customValue>
    <customValue>
        <fullName>34</fullName>
        <label>Home Contents</label>
    </customValue>
    <customValue>
        <fullName>35</fullName>
        <label>Business</label>
    </customValue>
    <customValue>
        <fullName>36</fullName>
        <label>Property</label>
    </customValue>
    <customValue>
        <fullName>37</fullName>
        <label>Other</label>
    </customValue>
    <masterLabel>AssetTypes</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/globalValueSets/AssetVehicleType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>38</fullName>
        <label>Motor Vehicle</label>
    </customValue>
    <customValue>
        <fullName>39</fullName>
        <label>Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>Boat</label>
    </customValue>
    <customValue>
        <fullName>41</fullName>
        <label>Campervan or Motorhome</label>
    </customValue>
    <customValue>
        <fullName>42</fullName>
        <label>Light Trailer or Caravan</label>
    </customValue>
    <masterLabel>AssetVehicleType</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/globalValueSets/PropertyCommercialTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>841</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>842</fullName>
        <label>Office</label>
    </customValue>
    <customValue>
        <fullName>843</fullName>
        <label>Industrial</label>
    </customValue>
    <masterLabel>PropertyCommercialTypes</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/classes/HLA_LoanApplicationAssetsSelector.cls
public inherited sharing class HLA_LoanApplicationAssetsSelector extends ApplicationSObjectSelector implements HLA_ILoanApplicationAssetsSelector {
  private String newOrderByField;
  private static String DEFAULT_ORDERBY_FIELD = 'Name';

  public static HLA_ILoanApplicationAssetsSelector newInstance() {
    return (HLA_ILoanApplicationAssetsSelector) Application.Selector.newInstance(
      LoanApplicationAsset__c.SObjectType
    );
  }

  // the list of fields to be included in query
  public override List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      LoanApplicationAsset__c.ResidentialLoanApplication__c,
      LoanApplicationAsset__c.Id,
      LoanApplicationAsset__c.Name,
      LoanApplicationAsset__c.ReferenceId__c,
      LoanApplicationAsset__c.ExternalId__c,
      LoanApplicationAsset__c.AssetSavingsAndDepositsType__c,
      LoanApplicationAsset__c.AssetSuperannuationType__c,
      LoanApplicationAsset__c.AssetType__c,
      LoanApplicationAsset__c.AssetVehicleType__c,
      LoanApplicationAsset__c.CommercialPropertyType__c,
      LoanApplicationAsset__c.Description__c,
      LoanApplicationAsset__c.EstimatedValue__c,
      LoanApplicationAsset__c.Motorcycles__c,
      LoanApplicationAsset__c.Vehicle__c,
      LoanApplicationAsset__c.isSecurityForLoanFinancingIt__c,
      LoanApplicationAsset__c.PropertyAddress__Street__s,
      LoanApplicationAsset__c.PropertyAddress__City__s,
      LoanApplicationAsset__c.PropertyAddress__PostalCode__s,
      LoanApplicationAsset__c.PropertyAddress__StateCode__s,
      LoanApplicationAsset__c.PropertyAddress__CountryCode__s,
      LoanApplicationAsset__c.isDirty__c
    };
  }

  // SObject type
  public Schema.SObjectType getSObjectType() {
    return LoanApplicationAsset__c.sObjectType;
  }

  @TestVisible
  private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
    return new List<Schema.SObjectField>{};
  }

  public override String getOrderBy() {
    if (newOrderByField != null) {
      DEFAULT_ORDERBY_FIELD = newOrderByField;
    }
    return DEFAULT_ORDERBY_FIELD;
  }

  public HLA_LoanApplicationAssetsSelector setNewSortOrder(
    String fieldToOrderBy
  ) {
    this.newOrderByField = fieldToOrderBy;
    return this;
  }

  /**
   * We will return List<Sobjects> and leave it to the caller to instatiate a Map if they need easy access to Id's
   */
  public List<LoanApplicationAsset__c> selectLoanApplicationAssetsByReferenceId(
    String referenceId,
    String applId
  ) {
    return (List<LoanApplicationAsset__c>) Database.query(
      newQueryFactory()
        .selectfield('Name')
        .setCondition(
          'ReferenceId__c = :referenceId AND ResidentialLoanApplication__c = :applId'
        )
        .toSOQL()
    );
  }
}