ctm-sf-homeloan-app/main/default/objects/LoanApplicationIncome__c/LoanApplicationIncome__c.object-meta.xml
<CustomObject>
    <label>Loan Application Income</label>
    <nameField>
        <label>Loan Application Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Income</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationIncome__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periods</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationIncome__c/fields/IncomeGovernmentBenefitsType__c.field-meta.xml
<CustomField>
    <fullName>IncomeGovernmentBenefitsType__c</fullName>
    <label>Income Government Benefits Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IncomeGovernmentBenefitsType</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationIncome__c/fields/IncomeMaintenanceChildSupportType__c.field-meta.xml
<CustomField>
    <fullName>IncomeMaintenanceChildSupportType__c</fullName>
    <label>Income Maintenance Child Support Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IncomeMaintenanceChildSupportType</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationIncome__c/fields/IncomeOtherType__c.field-meta.xml
<CustomField>
    <fullName>IncomeOtherType__c</fullName>
    <label>Income Other Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IncomeOtherType</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationIncome__c/fields/IncomeRentalType__c.field-meta.xml
<CustomField>
    <fullName>IncomeRentalType__c</fullName>
    <label>Income Rental Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IncomeRentalType</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationIncome__c/fields/IncomeRetirementType__c.field-meta.xml
<CustomField>
    <fullName>IncomeRetirementType__c</fullName>
    <label>Income Retirement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IncomeRetirementType</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationIncome__c/fields/OwnershipPercentage__c.field-meta.xml
<CustomField>
    <fullName>OwnershipPercentage__c</fullName>
    <label>Ownership Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationIncome__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Application Income</relationshipLabel>
    <relationshipName>Loan_Application_Income</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationIncome__c/fields/TaxType__c.field-meta.xml
<CustomField>
    <fullName>TaxType__c</fullName>
    <label>Tax Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IncomeTaxTypes</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationIncome__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IncomeTypes</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/globalValueSets/IncomeGovernmentBenefitsType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>730</fullName>
        <label>Family Tax Benefit - Part A and B</label>
    </customValue>
    <customValue>
        <fullName>731</fullName>
        <label>Government Pension</label>
    </customValue>
    <customValue>
        <fullName>732</fullName>
        <label>Other</label>
    </customValue>
    <masterLabel>IncomeGovernmentBenefitsType</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/globalValueSets/IncomeMaintenanceChildSupportType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>746</fullName>
        <label>Spousal Maintenance</label>
    </customValue>
    <customValue>
        <fullName>747</fullName>
        <label>Child Support</label>
    </customValue>
    <customValue>
        <fullName>748</fullName>
        <label>Other</label>
    </customValue>
    <masterLabel>IncomeMaintenanceChildSupportType</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/globalValueSets/IncomeOtherType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>749</fullName>
        <label>Foreign Income</label>
    </customValue>
    <customValue>
        <fullName>750</fullName>
        <label>Non-Taxable Income</label>
    </customValue>
    <customValue>
        <fullName>751</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>752</fullName>
        <label>Paid Parental Leave</label>
    </customValue>
    <customValue>
        <fullName>753</fullName>
        <label>Employer Maternity Leave</label>
    </customValue>
    <masterLabel>IncomeOtherType</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/globalValueSets/IncomeRentalType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1666</fullName>
        <label>Short-term</label>
    </customValue>
    <customValue>
        <fullName>1667</fullName>
        <label>Long-term</label>
    </customValue>
    <customValue>
        <fullName>1816</fullName>
        <label>Commercial</label>
    </customValue>
    <masterLabel>IncomeRentalType</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/globalValueSets/IncomeRetirementType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>754</fullName>
        <label>Account-based Pension</label>
    </customValue>
    <customValue>
        <fullName>755</fullName>
        <label>Allocated Pension</label>
    </customValue>
    <customValue>
        <fullName>756</fullName>
        <label>Lifetime Annuity</label>
    </customValue>
    <customValue>
        <fullName>757</fullName>
        <label>Other</label>
    </customValue>
    <masterLabel>IncomeRetirementType</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/globalValueSets/IncomeTaxTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>758</fullName>
        <label>Net</label>
    </customValue>
    <customValue>
        <fullName>759</fullName>
        <label>Gross</label>
    </customValue>
    <masterLabel>IncomeTaxTypes</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/globalValueSets/IncomeTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>760</fullName>
        <label>Savings and Cash</label>
    </customValue>
    <customValue>
        <fullName>761</fullName>
        <label>Investment</label>
    </customValue>
    <customValue>
        <fullName>762</fullName>
        <label>Retirement Income</label>
    </customValue>
    <customValue>
        <fullName>763</fullName>
        <label>Government Benefits</label>
    </customValue>
    <customValue>
        <fullName>764</fullName>
        <label>Maintenance / Child support</label>
    </customValue>
    <customValue>
        <fullName>765</fullName>
        <label>Other Income</label>
    </customValue>
    <customValue>
        <fullName>766</fullName>
        <label>Employment</label>
    </customValue>
    <customValue>
        <fullName>767</fullName>
        <label>Rental Income</label>
    </customValue>
    <customValue>
        <fullName>1834</fullName>
        <label>Asset</label>
    </customValue>
    <masterLabel>IncomeTypes</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/globalValueSets/Periods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>824</fullName>
        <label>Weekly</label>
    </customValue>
    <customValue>
        <fullName>825</fullName>
        <label>Fortnightly</label>
    </customValue>
    <customValue>
        <fullName>826</fullName>
        <label>Monthly</label>
    </customValue>
    <customValue>
        <fullName>827</fullName>
        <label>Quarterly</label>
    </customValue>
    <customValue>
        <fullName>828</fullName>
        <label>Half Yearly</label>
    </customValue>
    <customValue>
        <fullName>829</fullName>
        <label>Annually</label>
    </customValue>
    <masterLabel>Periods</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/classes/HLA_LoanApplicationIncomeSelector.cls
public inherited sharing class HLA_LoanApplicationIncomeSelector extends ApplicationSObjectSelector implements HLA_ILoanApplicationIncomeSelector {
  private String newOrderByField;
  private static String DEFAULT_ORDERBY_FIELD = 'Name';

  public static HLA_ILoanApplicationIncomeSelector newInstance() {
    return (HLA_ILoanApplicationIncomeSelector) Application.Selector.newInstance(
      LoanApplicationIncome__c.SObjectType
    );
  }

  // the list of fields to be included in query
  public override List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      LoanApplicationIncome__c.ResidentialLoanApplication__c,
      LoanApplicationIncome__c.Id,
      LoanApplicationIncome__c.ExternalId__c,
      LoanApplicationIncome__c.ReferenceId__c,
      LoanApplicationIncome__c.Name,
      LoanApplicationIncome__c.Amount__c,
      LoanApplicationIncome__c.Frequency__c,
      LoanApplicationIncome__c.isDirty__c,
      LoanApplicationIncome__c.OwnershipPercentage__c,
      LoanApplicationIncome__c.IncomeGovernmentBenefitsType__c,
      LoanApplicationIncome__c.IncomeMaintenanceChildSupportType__c,
      LoanApplicationIncome__c.IncomeOtherType__c,
      LoanApplicationIncome__c.IncomeRentalType__c,
      LoanApplicationIncome__c.IncomeRetirementType__c,
      LoanApplicationIncome__c.TaxType__c,
      LoanApplicationIncome__c.Type__c,
      LoanApplicationIncome__c.isDirty__c
    };
  }

  // SObject type
  public Schema.SObjectType getSObjectType() {
    return LoanApplicationIncome__c.sObjectType;
  }

  @TestVisible
  private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
    return new List<Schema.SObjectField>{};
  }

  public override String getOrderBy() {
    if (newOrderByField != null) {
      DEFAULT_ORDERBY_FIELD = newOrderByField;
    }
    return DEFAULT_ORDERBY_FIELD;
  }

  public HLA_LoanApplicationIncomeSelector setNewSortOrder(
    String fieldToOrderBy
  ) {
    this.newOrderByField = fieldToOrderBy;
    return this;
  }

  /**
   * We will return List<Sobjects> and leave it to the caller to instatiate a Map if they need easy access to Id's
   */

  public List<LoanApplicationIncome__c> selectLoanApplicationIncomesByReferenceId(
    String referenceId,
    String applId
  ) {
    return (List<LoanApplicationIncome__c>) Database.query(
      newQueryFactory()
        .selectfield('Name')
        .setCondition(
          'ReferenceId__c = :referenceId AND ResidentialLoanApplication__c = :applId'
        )
        .toSOQL()
    );
  }
}