ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/LoanApplicationProduct__c.object-meta.xml
<CustomObject>
    <label>Loan Application Product</label>
    <nameField>
        <label>Loan Application Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/actualcomparisonrate__c.field-meta.xml
<CustomField>
    <fullName>actualcomparisonrate__c</fullName>
    <label>Actual Comparison Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/Approval__c.field-meta.xml
<CustomField>
    <fullName>Approval__c</fullName>
    <formula>Lender__r.Approval__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approval</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/comparisonrate__c.field-meta.xml
<CustomField>
    <fullName>comparisonrate__c</fullName>
    <label>Comparison Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/ConditionalApproval__c.field-meta.xml
<CustomField>
    <fullName>ConditionalApproval__c</fullName>
    <formula>Lender__r.ConditionalApproval__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conditional Approval</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/dscr__c.field-meta.xml
<CustomField>
    <fullName>dscr__c</fullName>
    <label>DSCR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/DTI__c.field-meta.xml
<CustomField>
    <fullName>DTI__c</fullName>
    <description>The debt-to-income (DTI) ratio compares the amount of total debt to overall annual gross income (unshaded)</description>
    <inlineHelpText>The debt-to-income (DTI) ratio compares the amount of total debt to overall annual gross income (unshaded)</inlineHelpText>
    <label>DTI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/expenses__c.field-meta.xml
<CustomField>
    <fullName>expenses__c</fullName>
    <label>Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/FirstHomeBuyer__c.field-meta.xml
<CustomField>
    <fullName>FirstHomeBuyer__c</fullName>
    <formula>Lender__r.FirstHomeBuyer__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Home Buyer</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/fixedperiod__c.field-meta.xml
<CustomField>
    <fullName>fixedperiod__c</fullName>
    <label>Fixed Period</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/gearingratio__c.field-meta.xml
<CustomField>
    <fullName>gearingratio__c</fullName>
    <description>Gearing ratio compares your total liabilities (including the new loan) to your total assets (including proposed new loan), expressed as a percentage - unshaded</description>
    <inlineHelpText>Gearing ratio compares your total liabilities (including the new loan) to your total assets (including proposed new loan), expressed as a percentage - unshaded</inlineHelpText>
    <label>Gearing Ratio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/hemratio__c.field-meta.xml
<CustomField>
    <fullName>hemratio__c</fullName>
    <label>HEM Ratio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/IDH__c.field-meta.xml
<CustomField>
    <fullName>IDH__c</fullName>
    <description>Total Income available for debt and housing (IDH) compares the net income after living expenses and UMI buffer available to total fixed commitments (including proposed loan repayment(s)) - based on assessment rules</description>
    <inlineHelpText>Total Income available for debt and housing (IDH) compares the net income after living expenses and UMI buffer available to total fixed commitments (including proposed loan repayment(s)) - based on assessment rules</inlineHelpText>
    <label>IDH</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lender</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loan Application Products</relationshipLabel>
    <relationshipName>Loan_Application_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/LenderLogo__c.field-meta.xml
<CustomField>
    <fullName>LenderLogo__c</fullName>
    <formula>Lender__r.LenderLogo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lender Logo</label>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/LTI__c.field-meta.xml
<CustomField>
    <fullName>LTI__c</fullName>
    <description>The loan-to-income (LTI) ratio compares the new loan exposure to overall annual gross income (unshaded)</description>
    <inlineHelpText>The loan-to-income (LTI) ratio compares the new loan exposure to overall annual gross income (unshaded)</inlineHelpText>
    <label>LTI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/maxcapacity__c.field-meta.xml
<CustomField>
    <fullName>maxcapacity__c</fullName>
    <label>Max Capacity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/NDI__c.field-meta.xml
<CustomField>
    <fullName>NDI__c</fullName>
    <description>Net Disposable Income Ratio (NDI) compares the net disposable income available (UMI) to total fixed commitments (including proposed loan repayment(s)) - based on assessment rules</description>
    <inlineHelpText>Net Disposable Income Ratio (NDI) compares the net disposable income available (UMI) to total fixed commitments (including proposed loan repayment(s)) - based on assessment rules</inlineHelpText>
    <label>NDI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/NewPurchase__c.field-meta.xml
<CustomField>
    <fullName>NewPurchase__c</fullName>
    <formula>Lender__r.NewPurchase__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>New Purchase</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <description>Full name of the product</description>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/Refinance__c.field-meta.xml
<CustomField>
    <fullName>Refinance__c</fullName>
    <formula>Lender__r.Refinance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Refinance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/repayment__c.field-meta.xml
<CustomField>
    <fullName>repayment__c</fullName>
    <label>Repayment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/repaymentoption__c.field-meta.xml
<CustomField>
    <fullName>repaymentoption__c</fullName>
    <label>Repayment Option</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Application Products</relationshipLabel>
    <relationshipName>Loan_Application_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/rowhash__c.field-meta.xml
<CustomField>
    <fullName>rowhash__c</fullName>
    <label>Row Hash</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/TimetoFilePickUp__c.field-meta.xml
<CustomField>
    <fullName>TimetoFilePickUp__c</fullName>
    <formula>Lender__r.TimetoFilePickUp__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time to File Pick Up</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/umi__c.field-meta.xml
<CustomField>
    <fullName>umi__c</fullName>
    <description>Net Monthly Surplus or Uncommitted Monthly Income (UMI) is the income available each month, after all expenses and commitments and any required buffer amount have been factored in (including the proposed home loan repayments) - based on assessment rules</description>
    <inlineHelpText>Net Monthly Surplus or Uncommitted Monthly Income (UMI) is the income available each month, after all expenses and commitments and any required buffer amount have been factored in (including the proposed home loan repayments) - based on assessment rules</inlineHelpText>
    <label>Uncommitted Monthly Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/umibuffer__c.field-meta.xml
<CustomField>
    <fullName>umibuffer__c</fullName>
    <description>Monthly Surplus or Uncommitted Monthly Income (UMI) Buffer amount required by lenders to have available each month</description>
    <inlineHelpText>Monthly Surplus or Uncommitted Monthly Income (UMI) Buffer amount required by lenders to have available each month</inlineHelpText>
    <label>UMI Buffer</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/valuationfees__c.field-meta.xml
<CustomField>
    <fullName>valuationfees__c</fullName>
    <label>Valuation Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationProduct__c/fields/variablerate__c.field-meta.xml
<CustomField>
    <fullName>variablerate__c</fullName>
    <label>Variable Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/DTI__c.field-meta.xml
<CustomField>
    <fullName>DTI__c</fullName>
    <inlineHelpText>DTI stands for Debt-to-Income ratio. It is a measure used by lenders to assess a borrower&apos;s ability to manage their monthly debt payments in relation to their income.</inlineHelpText>
    <label>DTI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/IDH__c.field-meta.xml
<CustomField>
    <fullName>IDH__c</fullName>
    <label>IDH</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lender</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner - Home Loan</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Residential Loan Applications (Lender)</relationshipLabel>
    <relationshipName>Residential_Loan_Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/LenderLogo__c.field-meta.xml
<CustomField>
    <fullName>LenderLogo__c</fullName>
    <formula>if(LogoURL__c != &apos;&apos;, IMAGE(LogoURL__c,&apos;&apos;, 50,100), &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lender Logo</label>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/LTI__c.field-meta.xml
<CustomField>
    <fullName>LTI__c</fullName>
    <inlineHelpText>LTI stands for Loan-to-Income ratio. It is a measure used by lenders to assess the affordability of a loan based on the borrower&apos;s income, comparing the loan amount to their gross income.</inlineHelpText>
    <label>LTI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/UMI__c.field-meta.xml
<CustomField>
    <fullName>UMI__c</fullName>
    <inlineHelpText>Uncommitted monthly income refers to the portion of a borrower&apos;s income that is available after deducting their monthly debt obligations. It represents the amount of income that can be allocated towards new loan repayments, indicating the borrower&apos;s capacity to take on additional debt.</inlineHelpText>
    <label>UMI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ctm-sf-homeloan-app/main/default/classes/HLA_LoanApplicationProductsSelector.cls
public inherited sharing class HLA_LoanApplicationProductsSelector extends ApplicationSObjectSelector implements HLA_ILoanApplicationProductsSelector {
  private String newOrderByField;
  private static String DEFAULT_ORDERBY_FIELD = 'Name';

  public static HLA_ILoanApplicationProductsSelector newInstance() {
    return (HLA_ILoanApplicationProductsSelector) Application.Selector.newInstance(
      LoanApplicationProduct__c.SObjectType
    );
  }

  // the list of fields to be included in query
  public override List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      LoanApplicationProduct__c.Id,
      LoanApplicationProduct__c.LenderLogo__c,
      LoanApplicationProduct__c.Lender__c,
      LoanApplicationProduct__c.Name,
      LoanApplicationProduct__c.fixedperiod__c,
      LoanApplicationProduct__c.repaymentoption__c,
      LoanApplicationProduct__c.repayment__c,
      LoanApplicationProduct__c.comparisonrate__c,
      LoanApplicationProduct__c.actualcomparisonrate__c,
      LoanApplicationProduct__c.maxcapacity__c,
      LoanApplicationProduct__c.umi__c,
      LoanApplicationProduct__c.umibuffer__c,
      LoanApplicationProduct__c.dscr__c,
      LoanApplicationProduct__c.NDI__c,
      LoanApplicationProduct__c.LTI__c,
      LoanApplicationProduct__c.DTI__c,
      LoanApplicationProduct__c.IDH__c,
      LoanApplicationProduct__c.gearingratio__c,
      LoanApplicationProduct__c.hemratio__c,
      LoanApplicationProduct__c.NewPurchase__c,
      LoanApplicationProduct__c.Refinance__c,
      LoanApplicationProduct__c.FirstHomeBuyer__c,
      LoanApplicationProduct__c.TimetoFilePickUp__c,
      LoanApplicationProduct__c.ConditionalApproval__c,
      LoanApplicationProduct__c.Approval__c,
      LoanApplicationProduct__c.ResidentialLoanApplication__c,
      LoanApplicationProduct__c.rowhash__c,
      LoanApplicationProduct__c.variablerate__c,
      LoanApplicationProduct__c.valuationfees__c,
      LoanApplicationProduct__c.expenses__c,
      LoanApplicationProduct__c.ProductName__c,
      LoanApplicationProduct__c.SelectedProduct__c,
      LoanApplicationProduct__c.RecommendationOrder__c,      
      LoanApplicationProduct__c.PolicyStatus__c

    };
  }

  // SObject type
  public Schema.SObjectType getSObjectType() {
    return LoanApplicationProduct__c.sObjectType;
  }

  private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
    return new List<Schema.SObjectField>{};
  }

  public override String getOrderBy() {
    if (newOrderByField != null) {
      DEFAULT_ORDERBY_FIELD = newOrderByField;
    }
    return DEFAULT_ORDERBY_FIELD;
  }

  public HLA_LoanApplicationProductsSelector setNewSortOrder(
    String fieldToOrderBy
  ) {
    this.newOrderByField = fieldToOrderBy;
    return this;
  }

  /**
   * We will return List<Sobjects> and leave it to the caller to instatiate a Map if they need easy access to Id's
   */
  public List<LoanApplicationProduct__c> selectLoanApplicationProductsByApplicationId(
    Set<id> resiLoanIds
  ) {
    return (List<LoanApplicationProduct__c>) Database.query(
      newQueryFactory()
        .selectfield('Lender__r.logoRectangleUrl__c')
        .setCondition('ResidentialLoanApplication__c in :resiLoanIds')
        .toSOQL()
    );
  }

  public List<LoanApplicationProduct__c> selectUsingApplicationExternalIdInWhereClause(
    Set<String> applicationExternalIds
  ) {
    return (List<LoanApplicationProduct__c>) Database.query(
      newQueryFactory()
        .setCondition(
          'residentialloanapplication__c in (SELECT Id FROM residentialloanapplication__c WHERE applicationId__c IN :applicationExternalIds)'
        )
        .toSOQL()
    );
  }

  public List<LoanApplicationProduct__c> selectLoanApplicationProductsByApplicationIdOrderByRAC(
    Set<id> resiLoanIds
  ) {
    return (List<LoanApplicationProduct__c>) Database.query(
      newQueryFactory()
        .selectfield('Lender__r.logoRectangleUrl__c')
        .selectfield('Lender__r.Name')
        .setCondition('ResidentialLoanApplication__c in :resiLoanIds')
        .setOrdering(
          'repayment__c',
          fflib_QueryFactory.SortOrder.ASCENDING,
          true
        )
        .addOrdering(
          'actualcomparisonrate__c',
          fflib_QueryFactory.SortOrder.ASCENDING,
          true
        )
        .addOrdering(
          'comparisonrate__c',
          fflib_QueryFactory.SortOrder.ASCENDING,
          true
        )
        .toSOQL()
        .toLowerCase()
        .replaceFirst('select', 'select toLabel(PolicyCodes__c), ')
    );
  }
}