ctm-sf-homeloan-app/main/default/objects/Enum__c/Enum__c.object-meta.xml
<CustomObject>
    <label>Enum</label>
    <nameField>
        <label>Internal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/Enum__c/fields/DisplayName__c.field-meta.xml
<CustomField>
    <fullName>DisplayName__c</fullName>
    <label>Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/Enum__c/fields/EnumType__c.field-meta.xml
<CustomField>
    <fullName>EnumType__c</fullName>
    <label>Enum Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APIKeyTypes</fullName>
            </value>
            <value>
                <fullName>ApplicationStatusCodes</fullName>
            </value>
            <value>
                <fullName>ApplicationTypes</fullName>
            </value>
            <value>
                <fullName>AssetPropertyIntention</fullName>
            </value>
            <value>
                <fullName>AssetSavingsAndDepositsType</fullName>
            </value>
            <value>
                <fullName>AssetSuperannuationType</fullName>
            </value>
            <value>
                <fullName>AssetTypes</fullName>
            </value>
            <value>
                <fullName>AssetVehicleType</fullName>
            </value>
            <value>
                <fullName>AustralianStates</fullName>
            </value>
            <value>
                <fullName>ConfidenceBands</fullName>
            </value>
            <value>
                <fullName>ConsolidatedDebtTypes</fullName>
            </value>
            <value>
                <fullName>ContactNumberTypes</fullName>
            </value>
            <value>
                <fullName>ContactPreferences</fullName>
            </value>
            <value>
                <fullName>ContributionsSourceOfFunds</fullName>
            </value>
            <value>
                <fullName>ContributionType</fullName>
            </value>
            <value>
                <fullName>CostTypes</fullName>
            </value>
            <value>
                <fullName>Countries</fullName>
            </value>
            <value>
                <fullName>CreditCardRepaymentTypes</fullName>
            </value>
            <value>
                <fullName>CreditInstitutions</fullName>
            </value>
            <value>
                <fullName>DebtTypes</fullName>
            </value>
            <value>
                <fullName>DocumentationTypes</fullName>
            </value>
            <value>
                <fullName>DocumentCategories</fullName>
            </value>
            <value>
                <fullName>DocumentStatuses</fullName>
            </value>
            <value>
                <fullName>EmploymentIndustries</fullName>
            </value>
            <value>
                <fullName
        >EmploymentOccupationsClericalOrAdministrativeWorker</fullName>
                <label
        >EmploymentOccupationsClericalOrAdministrativeWorker</label>
            </value>
            <value>
                <fullName
        >EmploymentOccupationsCommunityOrPersonalServicesWorker</fullName>
                <label
        >EmploymentOccupationsCommunityOrPersonalServicesWorker</label>
            </value>
            <value>
                <fullName>EmploymentOccupationsLabourer</fullName>
            </value>
            <value>
                <fullName
        >EmploymentOccupationsMachineryOperatorOrDriver</fullName>
                <label>EmploymentOccupationsMachineryOperatorOrDriver</label>
            </value>
            <value>
                <fullName>EmploymentOccupationsManager</fullName>
            </value>
            <value>
                <fullName>EmploymentOccupationsProfessional</fullName>
            </value>
            <value>
                <fullName>EmploymentOccupationsSalesWorker</fullName>
            </value>
            <value>
                <fullName
        >EmploymentOccupationsTechnicalOrTradeWorkers</fullName>
                <label>EmploymentOccupationsTechnicalOrTradeWorkers</label>
            </value>
            <value>
                <fullName>EmploymentRoles</fullName>
            </value>
            <value>
                <fullName>EmploymentSectors</fullName>
            </value>
            <value>
                <fullName>EmploymentTypes</fullName>
            </value>
            <value>
                <fullName>EntityTypes</fullName>
            </value>
            <value>
                <fullName>EquityReleaseReasons</fullName>
            </value>
            <value>
                <fullName>EquityReleaseTypes</fullName>
            </value>
            <value>
                <fullName>ErrorMessages</fullName>
            </value>
            <value>
                <fullName>ExpenseDebtDetailTypes</fullName>
            </value>
            <value>
                <fullName>ExpenseDebtTypes</fullName>
            </value>
            <value>
                <fullName>ExpenseLivingDetailTypes</fullName>
            </value>
            <value>
                <fullName>ExpenseLivingPropertyDetailTypes</fullName>
            </value>
            <value>
                <fullName>ExpenseLivingTypes</fullName>
            </value>
            <value>
                <fullName>ExpenseTypes</fullName>
            </value>
            <value>
                <fullName>FinancialSources</fullName>
            </value>
            <value>
                <fullName>GoodBadDisplay</fullName>
            </value>
            <value>
                <fullName>IdentificationTypes</fullName>
            </value>
            <value>
                <fullName>IdentityVerificationLevels</fullName>
            </value>
            <value>
                <fullName>IncomeEmploymentTypes</fullName>
            </value>
            <value>
                <fullName>IncomeGovernmentBenefitsType</fullName>
            </value>
            <value>
                <fullName>IncomeInvestmentType</fullName>
            </value>
            <value>
                <fullName>IncomeMaintenanceChildSupportType</fullName>
            </value>
            <value>
                <fullName>IncomeOtherType</fullName>
            </value>
            <value>
                <fullName>IncomeRentalType</fullName>
            </value>
            <value>
                <fullName>IncomeRetirementType</fullName>
            </value>
            <value>
                <fullName>IncomeTaxTypes</fullName>
            </value>
            <value>
                <fullName>IncomeTypes</fullName>
            </value>
            <value>
                <fullName>InterestTypes</fullName>
            </value>
            <value>
                <fullName>LiabilityCardRepaymentType</fullName>
            </value>
            <value>
                <fullName>LiabilityTypes</fullName>
            </value>
            <value>
                <fullName>LivingSituations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/Enum__c/fields/GlobalPicklistAPIName__c.field-meta.xml
<CustomField>
    <fullName>GlobalPicklistAPIName__c</fullName>
    <label>GlobalPicklistAPIName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/Enum__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/HLA_EnumMapping__mdt/HLA_EnumMapping__mdt.object-meta.xml
<CustomObject>
    <description>maps enum types to global picklists</description>
    <label>HLA_Enum Mapping</label>
    <pluralLabel>HLA_Enum Mappings</pluralLabel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/HLA_EnumMapping__mdt/fields/GlobalPicklistAPIName__c.field-meta.xml
<CustomField>
    <fullName>GlobalPicklistAPIName__c</fullName>
    <label>Global Picklist API Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/classes/HLA_Enums.cls
public inherited sharing class HLA_Enums extends ApplicationSObjectDomain implements HLA_IEnums {
  private Map<String, List<EnumItem>> enumItemMap;

  public static HLA_IEnums newInstance(List<Enum__c> records) {
    return (HLA_IEnums) Application.Domain.newInstance(records);
  }

  public static HLA_IEnums newInstance(Set<Id> recordIds) {
    return (HLA_IEnums) Application.Domain.newInstance(recordIds);
  }

  public HLA_Enums(List<Enum__c> enums) {
    super(enums);
  }

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> sObjectList) {
      return new HLA_Enums(sObjectList);
    }
  }

  private List<Enum__c> enumsRecords {
    get {
      if (enumsRecords == null) {
        enumsRecords = (List<Enum__c>) records;
      }
      return enumsRecords;
    }
    private set;
  }

  private Map<String, HLA_EnumMapping__mdt> enumMappings {
    get {
      if (enumMappings == null) {
        enumMappings = new Map<String, HLA_EnumMapping__mdt>();
        enumMappings.putall(HLA_EnumMapping__mdt.getAll());
      }
      return enumMappings;
    }
    private set {
    }
  }

  public List<Enum__c> getEnumsRecords() {
    return this.enumsRecords;
  }

  public override void onBeforeInsert() {
    HLA_EnumService.setEnumValues(enumsRecords);
  }

  public override void onAfterInsert() {
    System.enqueueJob(
      new HLA_EnumUpdateRelatedPicklistsQueueable(enumsRecords)
    );
  }

  public override void onAfterUpdate(Map<Id, SObject> enumRecordsMap) {
    System.enqueueJob(
      new HLA_EnumUpdateRelatedPicklistsQueueable(enumsRecords)
    );
  }
  public override void onAfterDelete() {
    System.enqueueJob(
      new HLA_EnumUpdateRelatedPicklistsQueueable(enumsRecords)
    );
  }

  public void setEnumValues() {
    for (Enum__c en : (List<Enum__c>) records) {
      if (en.Value__c == null) {
        en.Value__c = nextEnumValue;
      }
      en.GlobalPicklistAPIName__c = enumMappings.get(en.EnumType__c)
        ?.GlobalPicklistAPIName__c;
    }
  }

  /* Returns the next available Enum Value__c
   * making it static incase it is called from multiple places in a single transaction
   * */
  public static Integer nextEnumValue {
    get {
      if (nextEnumValue == null) {
        List<Enum__c> enumFound = [
          SELECT value__c
          FROM Enum__c
          WHERE Value__c != NULL
          ORDER BY value__c DESC
          LIMIT 1
        ];
        nextEnumValue = Integer.valueOf(
          enumFound.isEmpty() ? 0 : enumFound[0].Value__c + 1
        );
      }
      return nextEnumValue++;
    }
    private set {
    }
  }

  public Map<String, List<EnumItem>> getEnumItemMap() {
    if (enumItemMap == null) {
      enumItemMap = new Map<String, List<EnumItem>>();
      for (Enum__c en : (List<Enum__c>) records) {
        EnumItem item = new EnumItem();
        item.enumName = en.Name;
        item.label = en.DisplayName__c;
        item.value = Integer.valueOf(en.Value__c);
        if (enumItemMap.containsKey(en.EnumType__c)) {
          enumItemMap.get(en.EnumType__c).add(item);
        } else {
          enumItemMap.put(en.EnumType__c, new List<EnumItem>{ item });
        }
      }
    }
    return enumItemMap;
  }

  public class EnumItem {
    public String label;
    public String enumName;
    public Integer value;
  }
}