ctm-sf-homeloan-app/main/default/objects/Enum__c/Enum__c.object-meta.xml
<CustomObject>
    <label>Enum</label>
    <nameField>
        <label>Internal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/Enum__c/fields/DisplayName__c.field-meta.xml
<CustomField>
    <fullName>DisplayName__c</fullName>
    <label>Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/Enum__c/fields/EnumType__c.field-meta.xml
<CustomField>
    <fullName>EnumType__c</fullName>
    <label>Enum Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APIKeyTypes</fullName>
            </value>
            <value>
                <fullName>ApplicationStatusCodes</fullName>
            </value>
            <value>
                <fullName>ApplicationTypes</fullName>
            </value>
            <value>
                <fullName>AssetPropertyIntention</fullName>
            </value>
            <value>
                <fullName>AssetSavingsAndDepositsType</fullName>
            </value>
            <value>
                <fullName>AssetSuperannuationType</fullName>
            </value>
            <value>
                <fullName>AssetTypes</fullName>
            </value>
            <value>
                <fullName>AssetVehicleType</fullName>
            </value>
            <value>
                <fullName>AustralianStates</fullName>
            </value>
            <value>
                <fullName>ConfidenceBands</fullName>
            </value>
            <value>
                <fullName>ConsolidatedDebtTypes</fullName>
            </value>
            <value>
                <fullName>ContactNumberTypes</fullName>
            </value>
            <value>
                <fullName>ContactPreferences</fullName>
            </value>
            <value>
                <fullName>ContributionsSourceOfFunds</fullName>
            </value>
            <value>
                <fullName>ContributionType</fullName>
            </value>
            <value>
                <fullName>CostTypes</fullName>
            </value>
            <value>
                <fullName>Countries</fullName>
            </value>
            <value>
                <fullName>CreditCardRepaymentTypes</fullName>
            </value>
            <value>
                <fullName>CreditInstitutions</fullName>
            </value>
            <value>
                <fullName>DebtTypes</fullName>
            </value>
            <value>
                <fullName>DocumentationTypes</fullName>
            </value>
            <value>
                <fullName>DocumentCategories</fullName>
            </value>
            <value>
                <fullName>DocumentStatuses</fullName>
            </value>
            <value>
                <fullName>EmploymentIndustries</fullName>
            </value>
            <value>
                <fullName
        >EmploymentOccupationsClericalOrAdministrativeWorker</fullName>
                <label
        >EmploymentOccupationsClericalOrAdministrativeWorker</label>
            </value>
            <value>
                <fullName
        >EmploymentOccupationsCommunityOrPersonalServicesWorker</fullName>
                <label
        >EmploymentOccupationsCommunityOrPersonalServicesWorker</label>
            </value>
            <value>
                <fullName>EmploymentOccupationsLabourer</fullName>
            </value>
            <value>
                <fullName
        >EmploymentOccupationsMachineryOperatorOrDriver</fullName>
                <label>EmploymentOccupationsMachineryOperatorOrDriver</label>
            </value>
            <value>
                <fullName>EmploymentOccupationsManager</fullName>
            </value>
            <value>
                <fullName>EmploymentOccupationsProfessional</fullName>
            </value>
            <value>
                <fullName>EmploymentOccupationsSalesWorker</fullName>
            </value>
            <value>
                <fullName
        >EmploymentOccupationsTechnicalOrTradeWorkers</fullName>
                <label>EmploymentOccupationsTechnicalOrTradeWorkers</label>
            </value>
            <value>
                <fullName>EmploymentRoles</fullName>
            </value>
            <value>
                <fullName>EmploymentSectors</fullName>
            </value>
            <value>
                <fullName>EmploymentTypes</fullName>
            </value>
            <value>
                <fullName>EntityTypes</fullName>
            </value>
            <value>
                <fullName>EquityReleaseReasons</fullName>
            </value>
            <value>
                <fullName>EquityReleaseTypes</fullName>
            </value>
            <value>
                <fullName>ErrorMessages</fullName>
            </value>
            <value>
                <fullName>ExpenseDebtDetailTypes</fullName>
            </value>
            <value>
                <fullName>ExpenseDebtTypes</fullName>
            </value>
            <value>
                <fullName>ExpenseLivingDetailTypes</fullName>
            </value>
            <value>
                <fullName>ExpenseLivingPropertyDetailTypes</fullName>
            </value>
            <value>
                <fullName>ExpenseLivingTypes</fullName>
            </value>
            <value>
                <fullName>ExpenseTypes</fullName>
            </value>
            <value>
                <fullName>FinancialSources</fullName>
            </value>
            <value>
                <fullName>GoodBadDisplay</fullName>
            </value>
            <value>
                <fullName>IdentificationTypes</fullName>
            </value>
            <value>
                <fullName>IdentityVerificationLevels</fullName>
            </value>
            <value>
                <fullName>IncomeEmploymentTypes</fullName>
            </value>
            <value>
                <fullName>IncomeGovernmentBenefitsType</fullName>
            </value>
            <value>
                <fullName>IncomeInvestmentType</fullName>
            </value>
            <value>
                <fullName>IncomeMaintenanceChildSupportType</fullName>
            </value>
            <value>
                <fullName>IncomeOtherType</fullName>
            </value>
            <value>
                <fullName>IncomeRentalType</fullName>
            </value>
            <value>
                <fullName>IncomeRetirementType</fullName>
            </value>
            <value>
                <fullName>IncomeTaxTypes</fullName>
            </value>
            <value>
                <fullName>IncomeTypes</fullName>
            </value>
            <value>
                <fullName>InterestTypes</fullName>
            </value>
            <value>
                <fullName>LiabilityCardRepaymentType</fullName>
            </value>
            <value>
                <fullName>LiabilityTypes</fullName>
            </value>
            <value>
                <fullName>LivingSituations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/Enum__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/classes/HLA_EnumServiceTest.cls
@IStest
public class HLA_EnumServiceTest {
  @IsTest
  public static void should_set_enum_value_to_next_available() {
    // Given

    Enum__c testEnum0 = new Enum__c();
    Enum__c testEnum1 = new Enum__c();
    List<Enum__c> enumList = new List<Enum__c>{ testEnum0, testEnum1 };

    // When
    test.startTest();
    HLA_EnumService.setEnumValues(enumList);
    test.stopTest();

    // Then
    System.assertEquals(0, testEnum0.value__c, 'should have set to 0');
    System.assertEquals(1, testEnum1.value__c, 'should have set to 1');
  }

  @IsTest
  public static void should_get_all_active_enums_mapped_by_type() {
    // Given
    fflib_ApexMocks mocks = new fflib_ApexMocks();

    HLA_IEnumsSelector mockEnumSelector = (HLA_IEnumsSelector) mocks.mock(
      HLA_EnumsSelector.class
    );

    Enum__c testEnum = new Enum__c(
      EnumType__c = 'AssetTypes',
      DisplayName__c = 'test',
      Name = 'test'
    );

    List<Enum__c> enumList = new List<Enum__c>{ testEnum };

    mocks.StartStubbing();
    mocks.when(mockEnumSelector.SObjectType()).thenReturn(Enum__c.sObjectType);
    mocks.when(mockEnumSelector.selectAllActiveEnums()).thenReturn(enumList);
    mocks.StopStubbing();

    Application.Selector.setMock(mockEnumSelector);

    // When
    test.startTest();
    Map<String, List<HLA_Enums.EnumItem>> enumMap = HLA_EnumService.getAllActiveEnumsMappedByType();
    test.stopTest();

    // Then

    System.assert(
      enumMap.containsKey('AssetTypes'),
      'should have added an enum entry for the test enum'
    );

    ((HLA_IEnumsSelector) mocks.verify(mockEnumSelector, 1))
      .selectAllActiveEnums();
  }
}