ctm-sf-homeloan-app/main/default/objects/LoanApplicantIncome__c/LoanApplicantIncome__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant Income</label>
    <nameField>
        <label>Loan Applicant Income</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicant Incomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantIncome__c/fields/BId__c.field-meta.xml
<CustomField>
    <fullName>BId__c</fullName>
    <formula>LoanApplicationIncome__r.ExternalId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BId</label>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantIncome__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <label>Percentage</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantIncome__c/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <description>Lookup to Loan Application Income Reference Field</description>
    <formula>LoanApplicationIncome__r.ReferenceId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ReferenceId</label>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantIncome__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Applicant Incomes</relationshipLabel>
    <relationshipName>Loan_Applicant_Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/classes/HLA_LoanApplicantIncomesSelector.cls
public inherited sharing class HLA_LoanApplicantIncomesSelector extends ApplicationSObjectSelector implements HLA_ILoanApplicantIncomesSelector {
  private String newOrderByField;
  private static String DEFAULT_ORDERBY_FIELD = 'Name';

  public static HLA_ILoanApplicantIncomesSelector newInstance() {
    return (HLA_ILoanApplicantIncomesSelector) Application.Selector.newInstance(
      LoanApplicantIncome__c.SObjectType
    );
  }

  // the list of fields to be included in query
  public override List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      LoanApplicantIncome__c.ResidentialLoanApplication__c,
      LoanApplicantIncome__c.Id,
      LoanApplicantIncome__c.Name,
      LoanApplicantIncome__c.ReferenceId__c,
      LoanApplicantIncome__c.ExternalId__c,
      LoanApplicantIncome__c.AId__c,
      LoanApplicantIncome__c.BId__c,
      LoanApplicantIncome__c.Percentage__c,
      LoanApplicantIncome__c.isDirty__c
    };
  }

  // SObject type
  public Schema.SObjectType getSObjectType() {
    return LoanApplicantIncome__c.sObjectType;
  }

  @TestVisible
  private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
    return new List<Schema.SObjectField>{};
  }

  public override String getOrderBy() {
    if (newOrderByField != null) {
      DEFAULT_ORDERBY_FIELD = newOrderByField;
    }
    return DEFAULT_ORDERBY_FIELD;
  }

  public HLA_LoanApplicantIncomesSelector setNewSortOrder(
    String fieldToOrderBy
  ) {
    this.newOrderByField = fieldToOrderBy;
    return this;
  }

  /**
   * We will return List<Sobjects> and leave it to the caller to instatiate a Map if they need easy access to Id's
   */

  public List<LoanApplicantIncome__c> selectLoanApplicantIncomesByReferenceId(
    String referenceId,
    String applId
  ) {
    return (List<LoanApplicantIncome__c>) Database.query(
      newQueryFactory()
        .selectfield('Name')
        .setCondition(
          'ReferenceId__c = :referenceId AND ResidentialLoanApplication__c = :applId'
        )
        .toSOQL()
    );
  }
}