ctm-sf-homeloan-app/main/default/objects/LoanApplicant__c/LoanApplicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Loan Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicant__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantLiability__c/LoanApplicantLiability__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant Liability</label>
    <nameField>
        <label>Loan Applicant Liability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicant Liabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantLiability__c/fields/LoanApplicant__c.field-meta.xml
<CustomField>
    <fullName>LoanApplicant__c</fullName>
    <label>Loan Applicant</label>
    <referenceTo>LoanApplicant__c</referenceTo>
    <relationshipLabel>Loan Applicant Liabilities</relationshipLabel>
    <relationshipName>Loan_Applicant_Liabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantLiability__c/fields/LoanApplicationLiability__c.field-meta.xml
<CustomField>
    <fullName>LoanApplicationLiability__c</fullName>
    <label>Loan Application Liability</label>
    <referenceTo>LoanApplicationLiability__c</referenceTo>
    <relationshipLabel>Loan Applicant Liabilities</relationshipLabel>
    <relationshipName>Loan_Applicant_Liabilities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/LoanApplicationLiability__c.object-meta.xml
<CustomObject>
    <label>Loan Application Liability</label>
    <nameField>
        <label>Loan Application Liability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Application Liabilities</relationshipLabel>
    <relationshipName>Loan_Application_Liabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Residential Loan Applications</relationshipLabel>
    <relationshipName>Residential_Loan_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/ApplicationId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationId__c</fullName>
    <externalId>true</externalId>
    <label>Application Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/classes/HLA_LoanApplicantLiabilityTriggerTest.cls
@IsTest
private class HLA_LoanApplicantLiabilityTriggerTest {
  @TestSetup
  static void makeData() {
    System.runAs(new User(Id = UserInfo.getUserId())) {
      PermissionSet ps = new PermissionSet(
        Name = 'CustomPermissionEnabled',
        Label = 'Custom Permisison Enabled'
      );
      insert ps;

      SetupEntityAccess sea = new SetupEntityAccess(
        ParentId = ps.Id,
        SetupEntityId = [
          SELECT Id
          FROM CustomPermission
          WHERE DeveloperName = 'CanSubmitApplicationChanges'
          LIMIT 1
        ]
        .Id
      );

      PermissionSetAssignment psa = new PermissionSetAssignment(
        AssigneeId = UserInfo.getUserId(),
        PermissionSetId = ps.Id
      );

      insert new List<SObject>{ sea, psa };
    }

    MockHttpResponseGenerator mockHttp = new MockHttpResponseGenerator();
    Test.setMock(HttpCalloutMock.class, mockHttp);

    Account testAcc = new Account(
      firstName = 'Test',
      lastName = 'Account',
      CustomerId__c = '123',
      recordtypeId = HLA_ResidentialLoanApplications.personAccountRTId
    );
    insert testAcc;
    ResidentialLoanApplication__c mockResi = new ResidentialLoanApplication__c(
      Account__c = testAcc.id,
      name = 'test RLA',
      ApplicationId__c = '123'
    );
    insert mockResi;

    LoanApplicant__c la = new loanApplicant__c();
    insert la;

    LoanApplicationLiability__c lal = new LoanApplicationLiability__c(
      ResidentialLoanApplication__c = mockResi.id
    );
    insert lal;

    LoanApplicantLiability__c testLal = new LoanApplicantLiability__c(
      name = 'test',
      loanApplicant__c = la.id,
      loanApplicationLiability__c = lal.id
    );
    insert testLal;
  }

  private static List<LoanApplicantLiability__c> getlalList() {
    return [SELECT Id FROM LoanApplicantLiability__c];
  }

  @IsTest
  public static void on_after_update_should_submit_updates() {
    MockHttpResponseGenerator mockHttp = new MockHttpResponseGenerator();
    MockHttpResponseGenerator.statusCodetoReturn = 301;
    Test.setMock(HttpCalloutMock.class, mockHttp);

    List<LoanApplicantLiability__c> lalList = getlalList();

    Test.startTest();
    System.runAs(new User(Id = UserInfo.getUserId())) {
      update lalList;
    }
    test.stopTest();

    Assert.areEqual(
      MockHttpResponseGenerator.calloutCounter,
      2,
      'should have generated 2 mock callout for update'
    );
  }

  @IsTest
  public static void on_after_delete_should_enqueue() {
    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

    List<LoanApplicantLiability__c> lalList = getlalList();

    Test.startTest();
    System.runAs(new User(Id = UserInfo.getUserId())) {
      delete lalList;
    }
    test.stopTest();

    /* delete currently commented out in trigger handler
    Assert.areEqual(
      MockHttpResponseGenerator.calloutCounter,
      1,
      'should have generated a mock callout for deletion'
    ); */
  }
}