ctm-sf-homeloan-app/main/default/objects/LoanApplicant__c/LoanApplicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Loan Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicant__c/fields/EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>EmailAddress__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicant__c/fields/PersonType__c.field-meta.xml
<CustomField>
    <fullName>PersonType__c</fullName>
    <label>Person Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PersonTypes</valueSetName>
    </valueSet>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicant__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Residential Loan Applications</relationshipLabel>
    <relationshipName>Residential_Loan_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/ApplicationId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationId__c</fullName>
    <externalId>true</externalId>
    <label>Application Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/globalValueSets/PersonTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>831</fullName>
        <label>Borrower</label>
    </customValue>
    <customValue>
        <fullName>832</fullName>
        <label>Guarantor</label>
    </customValue>
    <customValue>
        <fullName>833</fullName>
        <label>Professional Adviser</label>
    </customValue>
    <customValue>
        <fullName>834</fullName>
        <label>Related Party</label>
    </customValue>
    <masterLabel>PersonTypes</masterLabel>
</GlobalValueSet>

ctm-sf-homeloan-app/main/default/classes/HLA_LoanApplicantServiceTest.cls
@IsTest
public class HLA_LoanApplicantServiceTest {
  @TestSetup
  static void makeData() {
    IApplicationSObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
    MockHttpResponseGenerator mockHttp = new MockHttpResponseGenerator();
    Test.setMock(HttpCalloutMock.class, mockHttp);

    Account testAcc = new Account(
      firstName = 'Test',
      lastName = 'Account',
      PersonEmail = 'test@gmail.com',
      CustomerId__c = '123',
      recordtypeId = HLA_ResidentialLoanApplications.personAccountRTId
    );

    uow.register(testAcc);

    Contact testContact = new Contact(
      firstName = 'Test',
      lastName = 'Contact',
      Email = 'test@gmail.com',
      MobilePhone = '0400111222'
    );
    uow.register(testContact);

    ResidentialLoanApplication__c mockResi = new ResidentialLoanApplication__c(
      Account__c = testAcc.id,
      name = 'test RLA',
      ApplicationId__c = '123'
    );

    uow.register(mockResi, ResidentialLoanApplication__c.Account__c, testAcc);
    uow.commitwork();
  }

  @IsTest
  public static void should_not_attach_contacts_to_applicants_because_of_personType() {
    // Given

    fflib_ApexMocks mocks = new fflib_ApexMocks();

    IApplicationSObjectUnitOfWork mockUoW = (IApplicationSObjectUnitOfWork) mocks.mock(
      ApplicationSObjectUnitOfWork.class
    );
    Application.UnitOfWork.setMock(mockUoW);

    LoanApplicant__c testLoanApplicant = new LoanApplicant__c(
      ResidentialLoanApplication__c = fflib_IDGenerator.generate(
        ResidentialLoanApplication__c.SObjectType
      ),
      id = fflib_IDGenerator.generate(LoanApplicant__c.SObjectType),
      EmailAddress__c = 'test@gmail.com'
    );

    List<LoanApplicant__c> applicantList = new List<LoanApplicant__c>{
      testLoanApplicant
    };

    // When

    HLA_LoanApplicantService.attachContactsToApplicants(applicantList);

    // Then
    ((IApplicationSObjectUnitOfWork) mocks.verify(mockUoW, 0)).commitwork();
  }

  @IsTest
  public static void should_correctly_attach_contacts_to_applicants() {
    // Given

    fflib_ApexMocks mocks = new fflib_ApexMocks();

    IApplicationSObjectUnitOfWork mockUoW = (IApplicationSObjectUnitOfWork) mocks.mock(
      ApplicationSObjectUnitOfWork.class
    );
    Application.UnitOfWork.setMock(mockUoW);

    LoanApplicant__c testLoanApplicant = new LoanApplicant__c(
      ResidentialLoanApplication__c = fflib_IDGenerator.generate(
        ResidentialLoanApplication__c.SObjectType
      ),
      EmailAddress__c = 'test@gmail.com',
      PersonType__c = '831'
    );

    List<LoanApplicant__c> applicantList = new List<LoanApplicant__c>{
      testLoanApplicant
    };

    // When

    HLA_LoanApplicantService.attachContactsToApplicants(applicantList);

    // Then
    ((IApplicationSObjectUnitOfWork) mocks.verify(mockUoW, 1)).commitwork();
  }

  @IsTest
  public static void should_correctly_attach_new_contacts_to_applicants() {
    // Given

    fflib_ApexMocks mocks = new fflib_ApexMocks();

    IApplicationSObjectUnitOfWork mockUoW = (IApplicationSObjectUnitOfWork) mocks.mock(
      ApplicationSObjectUnitOfWork.class
    );
    Application.UnitOfWork.setMock(mockUoW);

    // test applicant with an email address that doesn't exists on any contacts - should create new
    LoanApplicant__c testLoanApplicant = new LoanApplicant__c(
      ResidentialLoanApplication__c = fflib_IDGenerator.generate(
        ResidentialLoanApplication__c.SObjectType
      ),
      EmailAddress__c = 'unknown@gmail.com',
      PersonType__c = '831'
    );

    List<LoanApplicant__c> applicantList = new List<LoanApplicant__c>{
      testLoanApplicant
    };

    // When
    Test.startTest();
    HLA_LoanApplicantService.attachContactsToApplicants(applicantList);
    Test.stopTest();

    // Then
    ((IApplicationSObjectUnitOfWork) mocks.verify(mockUoW, 1)).commitwork();
  }
}