ctm-sf-homeloan-app/main/default/objects/LoanApplicant__c/LoanApplicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Loan Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicant__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantAsset__c/LoanApplicantAsset__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant Asset</label>
    <nameField>
        <label>Loan Applicant Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicant Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantAsset__c/fields/LoanApplicant__c.field-meta.xml
<CustomField>
    <fullName>LoanApplicant__c</fullName>
    <label>Loan Applicant</label>
    <referenceTo>LoanApplicant__c</referenceTo>
    <relationshipLabel>Loan Applicant Assets</relationshipLabel>
    <relationshipName>Loan_Applicant_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantAsset__c/fields/LoanApplicationAsset__c.field-meta.xml
<CustomField>
    <fullName>LoanApplicationAsset__c</fullName>
    <label>Loan Application Asset</label>
    <referenceTo>LoanApplicationAsset__c</referenceTo>
    <relationshipLabel>Loan Applicant Assets</relationshipLabel>
    <relationshipName>Loan_Applicant_Assets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantAsset__c/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <description>Lookup to Loan Application Asset Reference Id</description>
    <formula>LoanApplicationAsset__r.ReferenceId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ReferenceId</label>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantAsset__c/fields/ResidentialLoanApplicationId__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplicationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Applicant Assets</relationshipLabel>
    <relationshipName>Loan_Applicant_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantExpense__c/LoanApplicantExpense__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant Expense</label>
    <nameField>
        <label>Loan Applicant Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicant Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantExpense__c/fields/LoanApplicant__c.field-meta.xml
<CustomField>
    <fullName>LoanApplicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>LoanApplicant__c</referenceTo>
    <relationshipLabel>Loan Applicant Expenses</relationshipLabel>
    <relationshipName>Loan_Applicant_Expenses1</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantExpense__c/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <description>Lookup to Loan Application Expense Reference Field</description>
    <formula>LoanApplicationExpense__r.ReferenceId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ReferenceId</label>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantExpense__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Applicant Expenses</relationshipLabel>
    <relationshipName>Loan_Applicant_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantIncome__c/LoanApplicantIncome__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant Income</label>
    <nameField>
        <label>Loan Applicant Income</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicant Incomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantIncome__c/fields/LoanApplicant__c.field-meta.xml
<CustomField>
    <fullName>LoanApplicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>LoanApplicant__c</referenceTo>
    <relationshipLabel>Loan Applicant Incomes</relationshipLabel>
    <relationshipName>Loan_Applicant_Incomes1</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantIncome__c/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <description>Lookup to Loan Application Income Reference Field</description>
    <formula>LoanApplicationIncome__r.ReferenceId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ReferenceId</label>
    <type>Text</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantIncome__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Applicant Incomes</relationshipLabel>
    <relationshipName>Loan_Applicant_Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantLiability__c/LoanApplicantLiability__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant Liability</label>
    <nameField>
        <label>Loan Applicant Liability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicant Liabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantLiability__c/fields/LoanApplicant__c.field-meta.xml
<CustomField>
    <fullName>LoanApplicant__c</fullName>
    <label>Loan Applicant</label>
    <referenceTo>LoanApplicant__c</referenceTo>
    <relationshipLabel>Loan Applicant Liabilities</relationshipLabel>
    <relationshipName>Loan_Applicant_Liabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantLiability__c/fields/LoanApplicationLiability__c.field-meta.xml
<CustomField>
    <fullName>LoanApplicationLiability__c</fullName>
    <label>Loan Application Liability</label>
    <referenceTo>LoanApplicationLiability__c</referenceTo>
    <relationshipLabel>Loan Applicant Liabilities</relationshipLabel>
    <relationshipName>Loan_Applicant_Liabilities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicantLiability__c/fields/ResidentialLoanApplicationId__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplicationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Applicant Liabilities</relationshipLabel>
    <relationshipName>Loan_Applicant_Liabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationAsset__c/LoanApplicationAsset__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Loan_Application_Asset_Compact_Layout</compactLayoutAssignment>
    <label>Loan Application Asset</label>
    <nameField>
        <label>Loan Application Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationAsset__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Application Assets</relationshipLabel>
    <relationshipName>Loan_Application_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationExpense__c/LoanApplicationExpense__c.object-meta.xml
<CustomObject>
    <label>Loan Application Expense</label>
    <nameField>
        <label>Loan Application Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Expense</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationExpense__c/fields/LoanApplicationLiability__c.field-meta.xml
<CustomField>
    <fullName>LoanApplicationLiability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application Liability</label>
    <referenceTo>LoanApplicationLiability__c</referenceTo>
    <relationshipLabel>Loan Application Expense</relationshipLabel>
    <relationshipName>Loan_Application_Expense</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationExpense__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Application Expense</relationshipLabel>
    <relationshipName>Loan_Application_Expense</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationIncome__c/LoanApplicationIncome__c.object-meta.xml
<CustomObject>
    <label>Loan Application Income</label>
    <nameField>
        <label>Loan Application Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Income</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationIncome__c/fields/LoanApplicationAsset__c.field-meta.xml
<CustomField>
    <fullName>LoanApplicationAsset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application Asset</label>
    <referenceTo>LoanApplicationAsset__c</referenceTo>
    <relationshipLabel>Loan Application Income</relationshipLabel>
    <relationshipName>Loan_Application_Income</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationIncome__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Application Income</relationshipLabel>
    <relationshipName>Loan_Application_Income</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/LoanApplicationLiability__c.object-meta.xml
<CustomObject>
    <label>Loan Application Liability</label>
    <nameField>
        <label>Loan Application Liability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/LoanApplicationAsset__c.field-meta.xml
<CustomField>
    <fullName>LoanApplicationAsset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application Asset</label>
    <referenceTo>LoanApplicationAsset__c</referenceTo>
    <relationshipLabel>Loan Application Liabilities</relationshipLabel>
    <relationshipName>Loan_Application_Liabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/LoanApplicationLiability__c/fields/ResidentialLoanApplication__c.field-meta.xml
<CustomField>
    <fullName>ResidentialLoanApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Loan Application</label>
    <referenceTo>ResidentialLoanApplication__c</referenceTo>
    <relationshipLabel>Loan Application Liabilities</relationshipLabel>
    <relationshipName>Loan_Application_Liabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/ResidentialLoanApplication__c.object-meta.xml
<CustomObject>
    <label>Residential Loan Application</label>
    <nameField>
        <label>Residential Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Residential Loan Applications</relationshipLabel>
    <relationshipName>Residential_Loan_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ctm-sf-homeloan-app/main/default/objects/ResidentialLoanApplication__c/fields/ApplicationId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationId__c</fullName>
    <externalId>true</externalId>
    <label>Application Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ctm-sf-homeloan-app/main/default/classes/HLA_TestDataFactory.cls
public class HLA_TestDataFactory {
  public static void makeData() {
    IApplicationSObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

    Account testAcc = new Account(
      firstName = 'Test',
      lastName = 'Account',
      CustomerId__c = '123',
      recordtypeId = HLA_ResidentialLoanApplications.personAccountRTId
    );
    uow.register(testAcc);

    ResidentialLoanApplication__c mockResi = new ResidentialLoanApplication__c(
      Account__c = testAcc.id,
      name = 'test RLA',
      ApplicationId__c = '123'
    );

    uow.register(mockResi, ResidentialLoanApplication__c.Account__c, testAcc);

    LoanApplicationAsset__c testLoanApplicationAsset = new LoanApplicationAsset__c(
      ResidentialLoanApplication__c = mockResi.id
    );

    uow.register(
      testLoanApplicationAsset,
      LoanApplicationAsset__c.ResidentialLoanApplication__c,
      mockResi
    );

    LoanApplicant__c testLoanApplicant = new LoanApplicant__c(
      ResidentialLoanApplication__c = mockResi.id
    );
    uow.register(
      testLoanApplicant,
      LoanApplicant__c.ResidentialLoanApplication__c,
      mockResi
    );

    LoanApplicantAsset__c testLoanApplicantAsset = new LoanApplicantAsset__c(
      Name = 'LoanApplicant Test',
      ResidentialLoanApplicationId__c = mockResi.id,
      LoanApplicant__c = testLoanApplicant.id,
      LoanApplicationAsset__c = testLoanApplicationAsset.id
    );

    uow.register(
      testLoanApplicantAsset,
      LoanApplicantAsset__c.LoanApplicant__c,
      testLoanApplicant
    );
    uow.registerRelationship(
      testLoanApplicantAsset,
      LoanApplicantAsset__c.LoanApplicationAsset__c,
      testLoanApplicationAsset
    );

    LoanApplicationLiability__c testLoanApplicationLiability = new LoanApplicationLiability__c(
      ResidentialLoanApplication__c = mockResi.id,
      ReferenceId__c = '123Abc-456def'
    );

    uow.register(
      testLoanApplicationLiability,
      LoanApplicationLiability__c.ResidentialLoanApplication__c,
      mockResi
    );

    LoanApplicantLiability__c testLoanApplicantLiability = new LoanApplicantLiability__c(
      Name = 'LoanApplicant Test',
      ResidentialLoanApplicationId__c = mockResi.id,
      LoanApplicant__c = testLoanApplicant.id,
      LoanApplicationLiability__c = testLoanApplicationLiability.id
    );

    uow.register(
      testLoanApplicantLiability,
      LoanApplicantLiability__c.LoanApplicant__c,
      testLoanApplicant
    );
    uow.registerRelationship(
      testLoanApplicantLiability,
      LoanApplicantLiability__c.LoanApplicationLiability__c,
      testLoanApplicationLiability
    );

    LoanApplicationIncome__c testLoanApplicationIncome = new LoanApplicationIncome__c(
      ResidentialLoanApplication__c = mockResi.id,
      ReferenceId__c = '123Abc-456def'
    );

    uow.register(
      testLoanApplicationIncome,
      LoanApplicationIncome__c.ResidentialLoanApplication__c,
      mockResi
    );

    LoanApplicantIncome__c testLoanApplicantIncome = new LoanApplicantIncome__c(
      ResidentialLoanApplication__c = mockResi.id,
      LoanApplicationIncome__c = testLoanApplicationIncome.id
    );

    uow.register(
      testLoanApplicantIncome,
      LoanApplicantIncome__c.LoanApplicationIncome__c,
      testLoanApplicationIncome
    );

    uow.registerRelationship(
      testLoanApplicantIncome,
      LoanApplicantIncome__c.LoanApplicationIncome__c,
      testLoanApplicationIncome
    );

    LoanApplicationExpense__c testLoanApplicationExpense = new LoanApplicationExpense__c(
      ResidentialLoanApplication__c = mockResi.id,
      ReferenceId__c = '123Abc-456def'
    );
    uow.register(
      testLoanApplicationExpense,
      LoanApplicationExpense__c.ResidentialLoanApplication__c,
      mockResi
    );

    LoanApplicantExpense__c testLoanApplicantExpense = new LoanApplicantExpense__c(
      ResidentialLoanApplication__c = mockResi.id,
      LoanApplicationExpense__c = testLoanApplicationExpense.id
    );

    uow.register(
      testLoanApplicantExpense,
      LoanApplicantExpense__c.LoanApplicationExpense__c,
      testLoanApplicationExpense
    );

    uow.registerRelationship(
      testLoanApplicantExpense,
      LoanApplicantExpense__c.LoanApplicationExpense__c,
      testLoanApplicationExpense
    );

    uow.commitwork();
  }
}